// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package workspacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteWorkspace(ctx context.Context, id pgtype.UUID) error
	GetMemberRoleName(ctx context.Context, arg GetMemberRoleNameParams) (string, error)
	GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error)
	GetWorkspaceByNameAndOwner(ctx context.Context, arg GetWorkspaceByNameAndOwnerParams) (Workspace, error)
	GetWorkspaceBySlugAndOwner(ctx context.Context, arg GetWorkspaceBySlugAndOwnerParams) (Workspace, error)
	GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (Workspace, error)
	GetWorkspaceSummary(ctx context.Context, workspaceID pgtype.UUID) (GetWorkspaceSummaryRow, error)
	GetWorkspaces(ctx context.Context, userID pgtype.UUID) ([]GetWorkspacesRow, error)
	GetWorkspacesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Workspace, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	// NULL means "automatic from the slug", the default every room is born with.
	UpdateWorkspaceHeroPreset(ctx context.Context, arg UpdateWorkspaceHeroPresetParams) (Workspace, error)
	// NULL clears the logo. The object is written before this runs and removed
	// after, so the row never points at a key that does not exist.
	UpdateWorkspaceLogo(ctx context.Context, arg UpdateWorkspaceLogoParams) (Workspace, error)
	UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
