// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package workspacedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
insert into workspaces 
    (owner_id, name, slug, description, status)
values 
    ($1, $2, $3, $4, $5)
returning id, owner_id, name, slug, description, status, created_at, updated_at
`

type CreateWorkspaceParams struct {
	OwnerID     pgtype.UUID `json:"owner_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Status,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
delete from workspaces where id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
select id, owner_id, name, slug, description, status, created_at, updated_at from workspaces where id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByNameAndOwner = `-- name: GetWorkspaceByNameAndOwner :one
select id, owner_id, name, slug, description, status, created_at, updated_at from workspaces 
where owner_id = $1 and name = $2
`

type GetWorkspaceByNameAndOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
}

func (q *Queries) GetWorkspaceByNameAndOwner(ctx context.Context, arg GetWorkspaceByNameAndOwnerParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByNameAndOwner, arg.OwnerID, arg.Name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlugAndOwner = `-- name: GetWorkspaceBySlugAndOwner :one
select id, owner_id, name, slug, description, status, created_at, updated_at from workspaces 
where owner_id = $1 and slug = $2
`

type GetWorkspaceBySlugAndOwnerParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetWorkspaceBySlugAndOwner(ctx context.Context, arg GetWorkspaceBySlugAndOwnerParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlugAndOwner, arg.OwnerID, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceForMember = `-- name: GetWorkspaceForMember :one
select w.id, w.owner_id, w.name, w.slug, w.description, w.status, w.created_at, w.updated_at from workspaces w
join workspace_members m on m.workspace_id = w.id
where w.id = $1
  and m.user_id = $2
  and m.status = 'active'
`

type GetWorkspaceForMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceForMember(ctx context.Context, arg GetWorkspaceForMemberParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForMember, arg.WorkspaceID, arg.UserID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaces = `-- name: GetWorkspaces :many
select
    w.id, w.owner_id, w.name, w.slug, w.description, w.status, w.created_at, w.updated_at,
    r.name as role_name,
    (
        select max(a.created_at)
        from activity_logs a
        where a.workspace_id = w.id
    )::timestamptz as last_activity_at
from workspaces w
join workspace_members wm on wm.workspace_id = w.id
join workspace_roles r on r.id = wm.role_id
where wm.user_id = $1
  and wm.status = 'active'
order by last_activity_at desc nulls last, w.created_at desc, w.id
`

type GetWorkspacesRow struct {
	ID             pgtype.UUID        `json:"id"`
	OwnerID        pgtype.UUID        `json:"owner_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    *string            `json:"description"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RoleName       string             `json:"role_name"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
}

func (q *Queries) GetWorkspaces(ctx context.Context, userID pgtype.UUID) ([]GetWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, getWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWorkspacesRow
	for rows.Next() {
		var i GetWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleName,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspacesByOwner = `-- name: GetWorkspacesByOwner :many
select id, owner_id, name, slug, description, status, created_at, updated_at from workspaces where owner_id = $1
`

func (q *Queries) GetWorkspacesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getWorkspacesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
update workspaces set
    name = $2,
    slug = $3,
    description = $4,
    updated_at = now()
where id = $1
returning id, owner_id, name, slug, description, status, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :one
update workspaces set 
    status = $1,
    updated_at = now()
where id = $2 and status = $3
returning id, owner_id, name, slug, description, status, created_at, updated_at
`

type UpdateWorkspaceStatusParams struct {
	Status     string      `json:"status"`
	ID         pgtype.UUID `json:"id"`
	FromStatus string      `json:"from_status"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceStatus, arg.Status, arg.ID, arg.FromStatus)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
