// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_user_invitations.sql

package invitationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptWorkspaceInvitation = `-- name: AcceptWorkspaceInvitation :one
update workspace_user_invitations set
    status = 'accepted',
    user_id = $2,
    accepted_at = now(),
    updated_at = now()
where id = $1 and status = 'pending'
returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id
`

type AcceptWorkspaceInvitationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AcceptWorkspaceInvitation(ctx context.Context, arg AcceptWorkspaceInvitationParams) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, acceptWorkspaceInvitation, arg.ID, arg.UserID)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const assignDefaultGroupIfGuest = `-- name: AssignDefaultGroupIfGuest :exec
insert into workspace_group_members (group_id, member_id)
select g.id, m.id
from workspace_members m
join workspace_roles r
    on r.id = m.role_id and r.name = 'guest'
join workspace_groups g
    on g.workspace_id = m.workspace_id and g.is_default
where m.workspace_id = $1 and m.user_id = $2
on conflict (member_id) do nothing
`

type AssignDefaultGroupIfGuestParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AssignDefaultGroupIfGuest(ctx context.Context, arg AssignDefaultGroupIfGuestParams) error {
	_, err := q.db.Exec(ctx, assignDefaultGroupIfGuest, arg.WorkspaceID, arg.UserID)
	return err
}

const assignToGroup = `-- name: AssignToGroup :exec
insert into workspace_group_members (group_id, member_id)
select g.id, m.id
from workspace_members m
join workspace_roles r
    on r.id = m.role_id and r.name = 'guest'
join workspace_groups g
    on g.id = $1 and g.workspace_id = m.workspace_id
where m.workspace_id = $2 and m.user_id = $3
on conflict (member_id) do nothing
`

type AssignToGroupParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

// Assigns the accepting guest to the group chosen at invite time. No-ops when
// the member is not a guest or the group does not belong to the workspace
// (invitations are validated on creation; this is defense in depth).
func (q *Queries) AssignToGroup(ctx context.Context, arg AssignToGroupParams) error {
	_, err := q.db.Exec(ctx, assignToGroup, arg.GroupID, arg.WorkspaceID, arg.UserID)
	return err
}

const getMyInvitations = `-- name: GetMyInvitations :many
select 
    wi.id, wi.workspace_id, wi.email, wi.role_id, wi.user_id, wi.invited_by, wi.code_hash, wi.status, wi.expires_at, wi.accepted_at, wi.created_at, wi.updated_at, wi.group_id,
    u.username as invited_name,
    r.name as role_name,
    w.name as workspace_name
from 
    workspace_user_invitations wi
left join
    workspaces w on w.id = wi.workspace_id
left join
    users u on u.id = wi.invited_by
left join
    workspace_roles r on r.id = wi.role_id
where wi.user_id = $1 and wi.status = 'pending' and wi.expires_at > now()
order by wi.created_at desc
`

type GetMyInvitationsRow struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	Email         string             `json:"email"`
	RoleID        pgtype.UUID        `json:"role_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	InvitedBy     pgtype.UUID        `json:"invited_by"`
	CodeHash      string             `json:"code_hash"`
	Status        string             `json:"status"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	GroupID       pgtype.UUID        `json:"group_id"`
	InvitedName   *string            `json:"invited_name"`
	RoleName      *string            `json:"role_name"`
	WorkspaceName *string            `json:"workspace_name"`
}

func (q *Queries) GetMyInvitations(ctx context.Context, userID pgtype.UUID) ([]GetMyInvitationsRow, error) {
	rows, err := q.db.Query(ctx, getMyInvitations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyInvitationsRow
	for rows.Next() {
		var i GetMyInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.RoleID,
			&i.UserID,
			&i.InvitedBy,
			&i.CodeHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.InvitedName,
			&i.RoleName,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceInvitation = `-- name: GetWorkspaceInvitation :one
select id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id from workspace_user_invitations where id = $1
`

func (q *Queries) GetWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitation, id)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :exec
insert into workspace_members
    (workspace_id, user_id, role_id, status)
values
    ($1, $2, $3, 'active')
on conflict (workspace_id, user_id) do nothing
`

type InsertMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	RoleID      pgtype.UUID `json:"role_id"`
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember, arg.WorkspaceID, arg.UserID, arg.RoleID)
	return err
}

const rejectWorkspaceInvitation = `-- name: RejectWorkspaceInvitation :one
update workspace_user_invitations set
    status = 'rejected',
    updated_at = now()
where id = $1 and status = 'pending'
returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id
`

func (q *Queries) RejectWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, rejectWorkspaceInvitation, id)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}
