// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qa.sql

package qadb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFaqs = `-- name: CountFaqs :one
select count(*) from faqs
where workspace_id = $1
`

func (q *Queries) CountFaqs(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFaqs, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countQuestions = `-- name: CountQuestions :one
select count(*) from questions
where workspace_id = $1
    and ($2::uuid is null or group_id = $2)
`

type CountQuestionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	GroupID     pgtype.UUID `json:"group_id"`
}

func (q *Queries) CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestions, arg.WorkspaceID, arg.GroupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWaitingQuestions = `-- name: CountWaitingQuestions :one
select count(*) from questions
where workspace_id = $1 and status = 'waiting'
`

func (q *Queries) CountWaitingQuestions(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitingQuestions, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocumentForRef = `-- name: GetDocumentForRef :one
select id, workspace_id, folder_id, name from documents
where id = $1 and deleted_at is null
`

type GetDocumentForRefRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetDocumentForRef(ctx context.Context, id pgtype.UUID) (GetDocumentForRefRow, error) {
	row := q.db.QueryRow(ctx, getDocumentForRef, id)
	var i GetDocumentForRefRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
	)
	return i, err
}

const getFolderForRef = `-- name: GetFolderForRef :one
select id, workspace_id, name from folders
where id = $1 and deleted_at is null
`

type GetFolderForRefRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetFolderForRef(ctx context.Context, id pgtype.UUID) (GetFolderForRefRow, error) {
	row := q.db.QueryRow(ctx, getFolderForRef, id)
	var i GetFolderForRefRow
	err := row.Scan(&i.ID, &i.WorkspaceID, &i.Name)
	return i, err
}

const getMemberGroupQA = `-- name: GetMemberGroupQA :one
select g.id, g.name, g.qa_enabled, g.qa_question_limit
from workspace_group_members gm
join workspace_members m on m.id = gm.member_id
join workspace_groups g on g.id = gm.group_id
where m.workspace_id = $1 and m.user_id = $2
`

type GetMemberGroupQAParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

type GetMemberGroupQARow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	QaEnabled       bool        `json:"qa_enabled"`
	QaQuestionLimit *int32      `json:"qa_question_limit"`
}

func (q *Queries) GetMemberGroupQA(ctx context.Context, arg GetMemberGroupQAParams) (GetMemberGroupQARow, error) {
	row := q.db.QueryRow(ctx, getMemberGroupQA, arg.WorkspaceID, arg.UserID)
	var i GetMemberGroupQARow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
select id, workspace_id, group_id, group_name, number, author_id, author_name, subject, body, status, document_id, document_name, folder_id, folder_name, created_at from questions
where id = $1 and workspace_id = $2
`

type GetQuestionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.ID, arg.WorkspaceID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.GroupName,
		&i.Number,
		&i.AuthorID,
		&i.AuthorName,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.DocumentID,
		&i.DocumentName,
		&i.FolderID,
		&i.FolderName,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionLocked = `-- name: GetQuestionLocked :one
select id, workspace_id, group_id, group_name, number, author_id, author_name, subject, body, status, document_id, document_name, folder_id, folder_name, created_at from questions
where id = $1
for update
`

func (q *Queries) GetQuestionLocked(ctx context.Context, id pgtype.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionLocked, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.GroupName,
		&i.Number,
		&i.AuthorID,
		&i.AuthorName,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.DocumentID,
		&i.DocumentName,
		&i.FolderID,
		&i.FolderName,
		&i.CreatedAt,
	)
	return i, err
}

const groupQuestionStats = `-- name: GroupQuestionStats :one
select
    count(*)::bigint as used,
    (coalesce(max(number), 0) + 1)::int as next_number
from questions
where group_id = $1
`

type GroupQuestionStatsRow struct {
	Used       int64 `json:"used"`
	NextNumber int32 `json:"next_number"`
}

func (q *Queries) GroupQuestionStats(ctx context.Context, groupID pgtype.UUID) (GroupQuestionStatsRow, error) {
	row := q.db.QueryRow(ctx, groupQuestionStats, groupID)
	var i GroupQuestionStatsRow
	err := row.Scan(&i.Used, &i.NextNumber)
	return i, err
}

const insertFaq = `-- name: InsertFaq :one
insert into faqs
    (workspace_id, question_text, answer_text, source_question_id, created_by, creator_name)
values
    ($1, $2, $3, $4, $5, $6)
returning id, workspace_id, question_text, answer_text, source_question_id, created_by, creator_name, created_at
`

type InsertFaqParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	QuestionText     string      `json:"question_text"`
	AnswerText       string      `json:"answer_text"`
	SourceQuestionID pgtype.UUID `json:"source_question_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
	CreatorName      string      `json:"creator_name"`
}

func (q *Queries) InsertFaq(ctx context.Context, arg InsertFaqParams) (Faq, error) {
	row := q.db.QueryRow(ctx, insertFaq,
		arg.WorkspaceID,
		arg.QuestionText,
		arg.AnswerText,
		arg.SourceQuestionID,
		arg.CreatedBy,
		arg.CreatorName,
	)
	var i Faq
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.QuestionText,
		&i.AnswerText,
		&i.SourceQuestionID,
		&i.CreatedBy,
		&i.CreatorName,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :one
insert into questions
    (workspace_id, group_id, group_name, number, author_id, author_name,
     subject, body, document_id, document_name, folder_id, folder_name)
values
    ($1, $2, $3, $4, $5, $6,
     $7, $8, $9, $10, $11, $12)
returning id, workspace_id, group_id, group_name, number, author_id, author_name, subject, body, status, document_id, document_name, folder_id, folder_name, created_at
`

type InsertQuestionParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	GroupID      pgtype.UUID `json:"group_id"`
	GroupName    string      `json:"group_name"`
	Number       int32       `json:"number"`
	AuthorID     pgtype.UUID `json:"author_id"`
	AuthorName   string      `json:"author_name"`
	Subject      string      `json:"subject"`
	Body         string      `json:"body"`
	DocumentID   pgtype.UUID `json:"document_id"`
	DocumentName string      `json:"document_name"`
	FolderID     pgtype.UUID `json:"folder_id"`
	FolderName   string      `json:"folder_name"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, insertQuestion,
		arg.WorkspaceID,
		arg.GroupID,
		arg.GroupName,
		arg.Number,
		arg.AuthorID,
		arg.AuthorName,
		arg.Subject,
		arg.Body,
		arg.DocumentID,
		arg.DocumentName,
		arg.FolderID,
		arg.FolderName,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.GroupID,
		&i.GroupName,
		&i.Number,
		&i.AuthorID,
		&i.AuthorName,
		&i.Subject,
		&i.Body,
		&i.Status,
		&i.DocumentID,
		&i.DocumentName,
		&i.FolderID,
		&i.FolderName,
		&i.CreatedAt,
	)
	return i, err
}

const insertReply = `-- name: InsertReply :one
insert into question_replies
    (question_id, author_id, author_name, author_role, body)
values
    ($1, $2, $3, $4, $5)
returning id, question_id, author_id, author_name, author_role, body, created_at
`

type InsertReplyParams struct {
	QuestionID pgtype.UUID `json:"question_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	AuthorName string      `json:"author_name"`
	AuthorRole string      `json:"author_role"`
	Body       string      `json:"body"`
}

func (q *Queries) InsertReply(ctx context.Context, arg InsertReplyParams) (QuestionReply, error) {
	row := q.db.QueryRow(ctx, insertReply,
		arg.QuestionID,
		arg.AuthorID,
		arg.AuthorName,
		arg.AuthorRole,
		arg.Body,
	)
	var i QuestionReply
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorRole,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listFaqs = `-- name: ListFaqs :many
select id, workspace_id, question_text, answer_text, source_question_id, created_by, creator_name, created_at from faqs
where workspace_id = $1
order by created_at desc, id desc
`

func (q *Queries) ListFaqs(ctx context.Context, workspaceID pgtype.UUID) ([]Faq, error) {
	rows, err := q.db.Query(ctx, listFaqs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Faq
	for rows.Next() {
		var i Faq
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.QuestionText,
			&i.AnswerText,
			&i.SourceQuestionID,
			&i.CreatedBy,
			&i.CreatorName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionReplies = `-- name: ListQuestionReplies :many
select id, question_id, author_id, author_name, author_role, body, created_at from question_replies
where question_id = $1
order by created_at asc, id asc
`

func (q *Queries) ListQuestionReplies(ctx context.Context, questionID pgtype.UUID) ([]QuestionReply, error) {
	rows, err := q.db.Query(ctx, listQuestionReplies, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionReply
	for rows.Next() {
		var i QuestionReply
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorRole,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
select
    q.id, q.workspace_id, q.group_id, q.group_name, q.number, q.author_id, q.author_name, q.subject, q.body, q.status, q.document_id, q.document_name, q.folder_id, q.folder_name, q.created_at,
    (select count(*) from question_replies qr where qr.question_id = q.id)::bigint as reply_count
from questions q
where q.workspace_id = $1
    and ($2::uuid is null or q.group_id = $2)
    and ($3::text is null or q.status = $3)
    and ($4::timestamptz is null
        or (q.created_at, q.id) < ($4::timestamptz, $5::uuid))
order by q.created_at desc, q.id desc
limit $6
`

type ListQuestionsParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	Status          *string            `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageSize        int32              `json:"page_size"`
}

type ListQuestionsRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	GroupName    string             `json:"group_name"`
	Number       int32              `json:"number"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	AuthorName   string             `json:"author_name"`
	Subject      string             `json:"subject"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	DocumentName string             `json:"document_name"`
	FolderID     pgtype.UUID        `json:"folder_id"`
	FolderName   string             `json:"folder_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ReplyCount   int64              `json:"reply_count"`
}

func (q *Queries) ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listQuestions,
		arg.WorkspaceID,
		arg.GroupID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsRow
	for rows.Next() {
		var i ListQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.GroupID,
			&i.GroupName,
			&i.Number,
			&i.AuthorID,
			&i.AuthorName,
			&i.Subject,
			&i.Body,
			&i.Status,
			&i.DocumentID,
			&i.DocumentName,
			&i.FolderID,
			&i.FolderName,
			&i.CreatedAt,
			&i.ReplyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroupQA = `-- name: LockGroupQA :one
select id, name, qa_enabled, qa_question_limit
from workspace_groups
where id = $1 and workspace_id = $2
for update
`

type LockGroupQAParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type LockGroupQARow struct {
	ID              pgtype.UUID `json:"id"`
	Name            string      `json:"name"`
	QaEnabled       bool        `json:"qa_enabled"`
	QaQuestionLimit *int32      `json:"qa_question_limit"`
}

func (q *Queries) LockGroupQA(ctx context.Context, arg LockGroupQAParams) (LockGroupQARow, error) {
	row := q.db.QueryRow(ctx, lockGroupQA, arg.GroupID, arg.WorkspaceID)
	var i LockGroupQARow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const updateQuestionStatus = `-- name: UpdateQuestionStatus :exec
update questions set status = $1 where id = $2
`

type UpdateQuestionStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateQuestionStatus(ctx context.Context, arg UpdateQuestionStatusParams) error {
	_, err := q.db.Exec(ctx, updateQuestionStatus, arg.Status, arg.ID)
	return err
}
