// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package qadb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountFaqs(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CountQuestions(ctx context.Context, arg CountQuestionsParams) (int64, error)
	CountWaitingQuestions(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	GetDocumentForRef(ctx context.Context, id pgtype.UUID) (GetDocumentForRefRow, error)
	GetFolderForRef(ctx context.Context, id pgtype.UUID) (GetFolderForRefRow, error)
	GetMemberGroupQA(ctx context.Context, arg GetMemberGroupQAParams) (GetMemberGroupQARow, error)
	GetQuestion(ctx context.Context, arg GetQuestionParams) (Question, error)
	GetQuestionLocked(ctx context.Context, id pgtype.UUID) (Question, error)
	GroupQuestionStats(ctx context.Context, groupID pgtype.UUID) (GroupQuestionStatsRow, error)
	InsertFaq(ctx context.Context, arg InsertFaqParams) (Faq, error)
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error)
	InsertReply(ctx context.Context, arg InsertReplyParams) (QuestionReply, error)
	ListFaqs(ctx context.Context, workspaceID pgtype.UUID) ([]Faq, error)
	ListQuestionReplies(ctx context.Context, questionID pgtype.UUID) ([]QuestionReply, error)
	ListQuestions(ctx context.Context, arg ListQuestionsParams) ([]ListQuestionsRow, error)
	LockGroupQA(ctx context.Context, arg LockGroupQAParams) (LockGroupQARow, error)
	UpdateQuestionStatus(ctx context.Context, arg UpdateQuestionStatusParams) error
}

var _ Querier = (*Queries)(nil)
