// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accessdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	ActorName   string             `json:"actor_name"`
	ActorRole   string             `json:"actor_role"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	TargetName  string             `json:"target_name"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ContentEvent struct {
	ID           int64              `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	DocumentName string             `json:"document_name"`
	VersionID    pgtype.UUID        `json:"version_id"`
	PageNo       *int32             `json:"page_no"`
	EventType    string             `json:"event_type"`
	DurationMs   *int32             `json:"duration_ms"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorEmail   string             `json:"actor_email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	FolderID            pgtype.UUID        `json:"folder_id"`
	Name                string             `json:"name"`
	CurrentVersionID    pgtype.UUID        `json:"current_version_id"`
	UploadedBy          pgtype.UUID        `json:"uploaded_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Position            int32              `json:"position"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	DeletedRootFolderID pgtype.UUID        `json:"deleted_root_folder_id"`
	StagedVersionID     pgtype.UUID        `json:"staged_version_id"`
}

type DocumentDownloadJob struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	VersionID    pgtype.UUID        `json:"version_id"`
	RequestedBy  pgtype.UUID        `json:"requested_by"`
	DocumentName string             `json:"document_name"`
	VersionNo    int32              `json:"version_no"`
	PageCount    int32              `json:"page_count"`
	Status       string             `json:"status"`
	ObjectKey    string             `json:"object_key"`
	SizeBytes    int64              `json:"size_bytes"`
	Error        string             `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type DocumentPageText struct {
	VersionID  pgtype.UUID        `json:"version_id"`
	PageNo     int32              `json:"page_no"`
	Content    string             `json:"content"`
	TsvID      interface{}        `json:"tsv_id"`
	TsvEn      interface{}        `json:"tsv_en"`
	OcrAt      pgtype.Timestamptz `json:"ocr_at"`
	OcrError   *string            `json:"ocr_error"`
	TextSource string             `json:"text_source"`
	Words      []byte             `json:"words"`
}

type DocumentVersion struct {
	ID                 pgtype.UUID        `json:"id"`
	DocumentID         pgtype.UUID        `json:"document_id"`
	VersionNo          int32              `json:"version_no"`
	Mime               string             `json:"mime"`
	Size               int64              `json:"size"`
	StorageKey         string             `json:"storage_key"`
	UploadedBy         pgtype.UUID        `json:"uploaded_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RenditionKey       *string            `json:"rendition_key"`
	PageCount          *int32             `json:"page_count"`
	RenditionError     *string            `json:"rendition_error"`
	RenditionFailedAt  pgtype.Timestamptz `json:"rendition_failed_at"`
	TextExtractedAt    pgtype.Timestamptz `json:"text_extracted_at"`
	TextError          *string            `json:"text_error"`
	TextFailedAt       pgtype.Timestamptz `json:"text_failed_at"`
	RenditionAttempts  int32              `json:"rendition_attempts"`
	RenditionNextAt    pgtype.Timestamptz `json:"rendition_next_at"`
	RenditionClaimedAt pgtype.Timestamptz `json:"rendition_claimed_at"`
}

type Faq struct {
	ID               pgtype.UUID        `json:"id"`
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	QuestionText     string             `json:"question_text"`
	AnswerText       string             `json:"answer_text"`
	SourceQuestionID pgtype.UUID        `json:"source_question_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatorName      string             `json:"creator_name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Folder struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	ParentID            pgtype.UUID        `json:"parent_id"`
	Name                string             `json:"name"`
	Position            int32              `json:"position"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	IsDefault           bool               `json:"is_default"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	DeletedRootFolderID pgtype.UUID        `json:"deleted_root_folder_id"`
}

type FolderAccess struct {
	FolderID            pgtype.UUID        `json:"folder_id"`
	GroupID             pgtype.UUID        `json:"group_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CanView             bool               `json:"can_view"`
	CanDownload         bool               `json:"can_download"`
	CanWatermark        bool               `json:"can_watermark"`
	CanDownloadOriginal bool               `json:"can_download_original"`
	CanShare            bool               `json:"can_share"`
}

type Question struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	GroupID      pgtype.UUID        `json:"group_id"`
	GroupName    string             `json:"group_name"`
	Number       int32              `json:"number"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	AuthorName   string             `json:"author_name"`
	Subject      string             `json:"subject"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	DocumentName string             `json:"document_name"`
	FolderID     pgtype.UUID        `json:"folder_id"`
	FolderName   string             `json:"folder_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type QuestionReply struct {
	ID         pgtype.UUID        `json:"id"`
	QuestionID pgtype.UUID        `json:"question_id"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	AuthorName string             `json:"author_name"`
	AuthorRole string             `json:"author_role"`
	Body       string             `json:"body"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	Username        *string            `json:"username"`
	PasswordHash    *string            `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Provider    string             `json:"provider"`
	ProviderUid string             `json:"provider_uid"`
	Email       *string            `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceArchive struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	RequestedBy     pgtype.UUID        `json:"requested_by"`
	RequestedByName string             `json:"requested_by_name"`
	Status          string             `json:"status"`
	ObjectKey       string             `json:"object_key"`
	SizeBytes       int64              `json:"size_bytes"`
	ChecksumSha256  string             `json:"checksum_sha256"`
	DocumentCount   int32              `json:"document_count"`
	MissingCount    int32              `json:"missing_count"`
	Error           string             `json:"error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type WorkspaceGroup struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	IsDefault       bool               `json:"is_default"`
	QaEnabled       bool               `json:"qa_enabled"`
	QaQuestionLimit *int32             `json:"qa_question_limit"`
}

type WorkspaceGroupMember struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceRole struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Permissions []string           `json:"permissions"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceUserInvitation struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	RoleID      pgtype.UUID        `json:"role_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	CodeHash    string             `json:"code_hash"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	GroupID     pgtype.UUID        `json:"group_id"`
}
