// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptWorkspaceInvitation(ctx context.Context, arg AcceptWorkspaceInvitationParams) (WorkspaceUserInvitation, error)
	AddMember(ctx context.Context, arg AddMemberParams) (WorkspaceMember, error)
	AssignDefaultGroupIfGuest(ctx context.Context, arg AssignDefaultGroupIfGuestParams) error
	// Assigns an accepting guest to the group chosen at invite time. No-ops when
	// the member is not a guest or the group belongs to another workspace
	// (invitations are validated on creation; this is defense in depth).
	AssignToGroup(ctx context.Context, arg AssignToGroupParams) error
	CreateDefaultGroup(ctx context.Context, arg CreateDefaultGroupParams) (WorkspaceGroup, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (WorkspaceGroup, error)
	DeleteGroup(ctx context.Context, id pgtype.UUID) error
	DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error
	DeleteMember(ctx context.Context, id pgtype.UUID) error
	GetDefaultGroup(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceGroup, error)
	GetGroup(ctx context.Context, id pgtype.UUID) (WorkspaceGroup, error)
	GetGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetGroupMembersRow, error)
	GetGroups(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceGroup, error)
	GetInvitationByCodeHashDetailed(ctx context.Context, codeHash string) (GetInvitationByCodeHashDetailedRow, error)
	GetMember(ctx context.Context, id pgtype.UUID) (GetMemberRow, error)
	GetMemberByWorkspaceUser(ctx context.Context, arg GetMemberByWorkspaceUserParams) (WorkspaceMember, error)
	GetMembers(ctx context.Context, workspaceID pgtype.UUID) ([]GetMembersRow, error)
	GetMembershipWithPermissions(ctx context.Context, arg GetMembershipWithPermissionsParams) (GetMembershipWithPermissionsRow, error)
	GetRole(ctx context.Context, id pgtype.UUID) (WorkspaceRole, error)
	GetRoles(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceRole, error)
	GetWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (GetWorkspaceInvitationRow, error)
	GetWorkspaceInvitationByCodeHash(ctx context.Context, codeHash string) (WorkspaceUserInvitation, error)
	GrantDefaultFolderAccess(ctx context.Context, arg GrantDefaultFolderAccessParams) error
	InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) (WorkspaceGroupMember, error)
	InsertRole(ctx context.Context, arg InsertRoleParams) (WorkspaceRole, error)
	InsertWorkspaceInvitation(ctx context.Context, arg InsertWorkspaceInvitationParams) (InsertWorkspaceInvitationRow, error)
	// A pending row whose expires_at has passed reads as 'expired': nothing flips
	// the stored status, so the lapse is derived here and the filter follows it.
	ListWorkspaceInvitations(ctx context.Context, arg ListWorkspaceInvitationsParams) ([]ListWorkspaceInvitationsRow, error)
	MoveGroupMembersToDefaultGroup(ctx context.Context, groupID pgtype.UUID) (int64, error)
	MoveMemberToDefaultGroup(ctx context.Context, memberID pgtype.UUID) (int64, error)
	ReinviteWorkspaceInvitation(ctx context.Context, arg ReinviteWorkspaceInvitationParams) (ReinviteWorkspaceInvitationRow, error)
	RejectWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error)
	ResendInvitation(ctx context.Context, arg ResendInvitationParams) (WorkspaceUserInvitation, error)
	RevokeWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (WorkspaceGroup, error)
	UpdateGroupQA(ctx context.Context, arg UpdateGroupQAParams) (WorkspaceGroup, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (WorkspaceMember, error)
}

var _ Querier = (*Queries)(nil)
