// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_group_member.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignDefaultGroupIfGuest = `-- name: AssignDefaultGroupIfGuest :exec
insert into workspace_group_members (group_id, member_id)
select g.id, m.id
from workspace_members m
join workspace_roles r
    on r.id = m.role_id and r.name = 'guest'
join workspace_groups g
    on g.workspace_id = m.workspace_id and g.is_default
where m.workspace_id = $1 and m.user_id = $2
on conflict (member_id) do nothing
`

type AssignDefaultGroupIfGuestParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AssignDefaultGroupIfGuest(ctx context.Context, arg AssignDefaultGroupIfGuestParams) error {
	_, err := q.db.Exec(ctx, assignDefaultGroupIfGuest, arg.WorkspaceID, arg.UserID)
	return err
}

const assignToGroup = `-- name: AssignToGroup :exec
insert into workspace_group_members (group_id, member_id)
select g.id, m.id
from workspace_members m
join workspace_roles r
    on r.id = m.role_id and r.name = 'guest'
join workspace_groups g
    on g.id = $1 and g.workspace_id = m.workspace_id
where m.workspace_id = $2 and m.user_id = $3
on conflict (member_id) do nothing
`

type AssignToGroupParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

// Assigns an accepting guest to the group chosen at invite time. No-ops when
// the member is not a guest or the group belongs to another workspace
// (invitations are validated on creation; this is defense in depth).
func (q *Queries) AssignToGroup(ctx context.Context, arg AssignToGroupParams) error {
	_, err := q.db.Exec(ctx, assignToGroup, arg.GroupID, arg.WorkspaceID, arg.UserID)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
delete from workspace_group_members where
    group_id = $1 and member_id = $2
`

type DeleteGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.MemberID)
	return err
}

const getGroupMembers = `-- name: GetGroupMembers :many
select
    gm.group_id, gm.member_id, gm.created_at,
    u.username,
    u.email,
    r.name as role_name,
    g.name as group_name
from
    workspace_group_members gm
left join
    workspace_groups g on g.id = gm.group_id
left join 
    workspace_members m on m.id = gm.member_id
left join
    users u on u.id = m.user_id
left join 
    workspace_roles r on r.id = m.role_id
where
    gm.group_id = $1
order by gm.created_at
`

type GetGroupMembersRow struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  *string            `json:"username"`
	Email     *string            `json:"email"`
	RoleName  *string            `json:"role_name"`
	GroupName *string            `json:"group_name"`
}

func (q *Queries) GetGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GetGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMembersRow
	for rows.Next() {
		var i GetGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
			&i.RoleName,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantDefaultFolderAccess = `-- name: GrantDefaultFolderAccess :exec
insert into folder_access (folder_id, group_id, can_view, can_download, can_watermark)
select f.id, $1, true, false, false
from folders f
where f.workspace_id = $2 and f.is_default
on conflict (folder_id, group_id) do nothing
`

type GrantDefaultFolderAccessParams struct {
	GroupID     pgtype.UUID `json:"group_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GrantDefaultFolderAccess(ctx context.Context, arg GrantDefaultFolderAccessParams) error {
	_, err := q.db.Exec(ctx, grantDefaultFolderAccess, arg.GroupID, arg.WorkspaceID)
	return err
}

const insertGroupMember = `-- name: InsertGroupMember :one
insert into workspace_group_members
    (group_id, member_id)
values
    ($1, $2)
on conflict (member_id) do update
    set group_id = excluded.group_id
returning group_id, member_id, created_at
`

type InsertGroupMemberParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	MemberID pgtype.UUID `json:"member_id"`
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) (WorkspaceGroupMember, error) {
	row := q.db.QueryRow(ctx, insertGroupMember, arg.GroupID, arg.MemberID)
	var i WorkspaceGroupMember
	err := row.Scan(&i.GroupID, &i.MemberID, &i.CreatedAt)
	return i, err
}

const moveGroupMembersToDefaultGroup = `-- name: MoveGroupMembersToDefaultGroup :execrows
update workspace_group_members gm
set group_id = dg.id
from workspace_members m, workspace_groups dg
where gm.member_id = m.id
  and dg.workspace_id = m.workspace_id
  and dg.is_default
  and gm.group_id = $1
`

func (q *Queries) MoveGroupMembersToDefaultGroup(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, moveGroupMembersToDefaultGroup, groupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveMemberToDefaultGroup = `-- name: MoveMemberToDefaultGroup :execrows
insert into workspace_group_members (group_id, member_id)
select g.id, m.id
from workspace_members m
join workspace_groups g
    on g.workspace_id = m.workspace_id and g.is_default
where m.id = $1
on conflict (member_id) do update
    set group_id = excluded.group_id
`

func (q *Queries) MoveMemberToDefaultGroup(ctx context.Context, memberID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, moveMemberToDefaultGroup, memberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
