// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_user_invitations.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptWorkspaceInvitation = `-- name: AcceptWorkspaceInvitation :one
update workspace_user_invitations set
    status = 'accepted',
    user_id = $2,
    accepted_at = now(),
    updated_at = now()
where id = $1 and status = 'pending'
returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at
`

type AcceptWorkspaceInvitationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AcceptWorkspaceInvitation(ctx context.Context, arg AcceptWorkspaceInvitationParams) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, acceptWorkspaceInvitation, arg.ID, arg.UserID)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
	)
	return i, err
}

const getInvitationByCodeHashDetailed = `-- name: GetInvitationByCodeHashDetailed :one
select 
    i.id, i.workspace_id, i.email, i.role_id, i.user_id, i.invited_by, i.code_hash, i.status, i.expires_at, i.accepted_at, i.created_at, i.updated_at, i.group_id, i.access_expires_at,
    w.name as workspace_name,
    r.name as role_name
from workspace_user_invitations i
join workspaces w on w.id = i.workspace_id
join workspace_roles r on r.id = i.role_id
where i.code_hash = $1
`

type GetInvitationByCodeHashDetailedRow struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Email           string             `json:"email"`
	RoleID          pgtype.UUID        `json:"role_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InvitedBy       pgtype.UUID        `json:"invited_by"`
	CodeHash        string             `json:"code_hash"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	GroupID         pgtype.UUID        `json:"group_id"`
	AccessExpiresAt pgtype.Timestamptz `json:"access_expires_at"`
	WorkspaceName   string             `json:"workspace_name"`
	RoleName        string             `json:"role_name"`
}

func (q *Queries) GetInvitationByCodeHashDetailed(ctx context.Context, codeHash string) (GetInvitationByCodeHashDetailedRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByCodeHashDetailed, codeHash)
	var i GetInvitationByCodeHashDetailedRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
		&i.WorkspaceName,
		&i.RoleName,
	)
	return i, err
}

const getWorkspaceInvitation = `-- name: GetWorkspaceInvitation :one
select
    i.id, i.workspace_id, i.email, i.role_id, i.user_id, i.invited_by, i.code_hash, i.status, i.expires_at, i.accepted_at, i.created_at, i.updated_at, i.group_id, i.access_expires_at,
    w.name as workspace_name,
    u.username as invited_by_username
from workspace_user_invitations i
join workspaces w on w.id = i.workspace_id
left join users u on u.id = i.invited_by
where i.id = $1
`

type GetWorkspaceInvitationRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Email             string             `json:"email"`
	RoleID            pgtype.UUID        `json:"role_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	InvitedBy         pgtype.UUID        `json:"invited_by"`
	CodeHash          string             `json:"code_hash"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	GroupID           pgtype.UUID        `json:"group_id"`
	AccessExpiresAt   pgtype.Timestamptz `json:"access_expires_at"`
	WorkspaceName     string             `json:"workspace_name"`
	InvitedByUsername *string            `json:"invited_by_username"`
}

func (q *Queries) GetWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (GetWorkspaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitation, id)
	var i GetWorkspaceInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
		&i.WorkspaceName,
		&i.InvitedByUsername,
	)
	return i, err
}

const getWorkspaceInvitationByCodeHash = `-- name: GetWorkspaceInvitationByCodeHash :one
select id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at from workspace_user_invitations where code_hash = $1
`

func (q *Queries) GetWorkspaceInvitationByCodeHash(ctx context.Context, codeHash string) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitationByCodeHash, codeHash)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
	)
	return i, err
}

const insertWorkspaceInvitation = `-- name: InsertWorkspaceInvitation :one
with created as (
    insert into workspace_user_invitations
        (workspace_id, email, role_id, user_id, group_id, invited_by, code_hash, status, expires_at, access_expires_at)
    values
        ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
    returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at
)
select
    i.id, i.workspace_id, i.email, i.role_id, i.user_id, i.invited_by, i.code_hash, i.status, i.expires_at, i.accepted_at, i.created_at, i.updated_at, i.group_id, i.access_expires_at,
    w.name as workspace_name,
    u.username as invited_by_username
from created i
join workspaces w on w.id = i.workspace_id
left join users u on u.id = i.invited_by
`

type InsertWorkspaceInvitationParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Email           string             `json:"email"`
	RoleID          pgtype.UUID        `json:"role_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	InvitedBy       pgtype.UUID        `json:"invited_by"`
	CodeHash        string             `json:"code_hash"`
	Status          string             `json:"status"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AccessExpiresAt pgtype.Timestamptz `json:"access_expires_at"`
}

type InsertWorkspaceInvitationRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Email             string             `json:"email"`
	RoleID            pgtype.UUID        `json:"role_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	InvitedBy         pgtype.UUID        `json:"invited_by"`
	CodeHash          string             `json:"code_hash"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	GroupID           pgtype.UUID        `json:"group_id"`
	AccessExpiresAt   pgtype.Timestamptz `json:"access_expires_at"`
	WorkspaceName     string             `json:"workspace_name"`
	InvitedByUsername *string            `json:"invited_by_username"`
}

func (q *Queries) InsertWorkspaceInvitation(ctx context.Context, arg InsertWorkspaceInvitationParams) (InsertWorkspaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceInvitation,
		arg.WorkspaceID,
		arg.Email,
		arg.RoleID,
		arg.UserID,
		arg.GroupID,
		arg.InvitedBy,
		arg.CodeHash,
		arg.Status,
		arg.ExpiresAt,
		arg.AccessExpiresAt,
	)
	var i InsertWorkspaceInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
		&i.WorkspaceName,
		&i.InvitedByUsername,
	)
	return i, err
}

const listWorkspaceInvitations = `-- name: ListWorkspaceInvitations :many
select
    i.id,
    i.workspace_id,
    i.email,
    i.role_id,
    i.user_id,
    i.invited_by,
    i.code_hash,
    (case
        when i.status = 'pending' and i.expires_at <= now() then 'expired'
        else i.status
    end)::text as status,
    i.expires_at,
    i.accepted_at,
    i.created_at,
    i.updated_at,
    i.group_id,
    i.access_expires_at,
    r.name as role_name,
    u.username as invited_by_username,
    g.name as group_name
from
    workspace_user_invitations i
left join
    workspace_roles r
        on r.id = i.role_id
left join
    users u
        on u.id = i.invited_by
left join
    workspace_groups g
        on g.id = i.group_id
where
    i.workspace_id = $1
    and (
        $2::text is null
        or case
            when i.status = 'pending' and i.expires_at <= now() then 'expired'
            else i.status
        end = $2
    )
order by i.created_at desc
`

type ListWorkspaceInvitationsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Status      *string     `json:"status"`
}

type ListWorkspaceInvitationsRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Email             string             `json:"email"`
	RoleID            pgtype.UUID        `json:"role_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	InvitedBy         pgtype.UUID        `json:"invited_by"`
	CodeHash          string             `json:"code_hash"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	GroupID           pgtype.UUID        `json:"group_id"`
	AccessExpiresAt   pgtype.Timestamptz `json:"access_expires_at"`
	RoleName          *string            `json:"role_name"`
	InvitedByUsername *string            `json:"invited_by_username"`
	GroupName         *string            `json:"group_name"`
}

// A pending row whose expires_at has passed reads as 'expired': nothing flips
// the stored status, so the lapse is derived here and the filter follows it.
func (q *Queries) ListWorkspaceInvitations(ctx context.Context, arg ListWorkspaceInvitationsParams) ([]ListWorkspaceInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceInvitations, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceInvitationsRow
	for rows.Next() {
		var i ListWorkspaceInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.RoleID,
			&i.UserID,
			&i.InvitedBy,
			&i.CodeHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.AccessExpiresAt,
			&i.RoleName,
			&i.InvitedByUsername,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reinviteWorkspaceInvitation = `-- name: ReinviteWorkspaceInvitation :one
with updated as (
    update workspace_user_invitations set
        status = 'pending',
        role_id = $1,
        user_id = $2,
        group_id = $3,
        invited_by = $4,
        code_hash = $5,
        expires_at = $6,
        access_expires_at = $7,
        accepted_at = null,
        updated_at = now()
    where workspace_id = $8
        and lower(email) = lower($9)
        and (
            status in ('revoked', 'rejected', 'expired')
            or (status = 'pending' and expires_at <= now())
        )
    returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at
)
select
    i.id, i.workspace_id, i.email, i.role_id, i.user_id, i.invited_by, i.code_hash, i.status, i.expires_at, i.accepted_at, i.created_at, i.updated_at, i.group_id, i.access_expires_at,
    w.name as workspace_name,
    u.username as invited_by_username
from updated i
join workspaces w on w.id = i.workspace_id
left join users u on u.id = i.invited_by
`

type ReinviteWorkspaceInvitationParams struct {
	RoleID          pgtype.UUID        `json:"role_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	InvitedBy       pgtype.UUID        `json:"invited_by"`
	CodeHash        string             `json:"code_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AccessExpiresAt pgtype.Timestamptz `json:"access_expires_at"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	Email           string             `json:"email"`
}

type ReinviteWorkspaceInvitationRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	Email             string             `json:"email"`
	RoleID            pgtype.UUID        `json:"role_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	InvitedBy         pgtype.UUID        `json:"invited_by"`
	CodeHash          string             `json:"code_hash"`
	Status            string             `json:"status"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt        pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	GroupID           pgtype.UUID        `json:"group_id"`
	AccessExpiresAt   pgtype.Timestamptz `json:"access_expires_at"`
	WorkspaceName     string             `json:"workspace_name"`
	InvitedByUsername *string            `json:"invited_by_username"`
}

func (q *Queries) ReinviteWorkspaceInvitation(ctx context.Context, arg ReinviteWorkspaceInvitationParams) (ReinviteWorkspaceInvitationRow, error) {
	row := q.db.QueryRow(ctx, reinviteWorkspaceInvitation,
		arg.RoleID,
		arg.UserID,
		arg.GroupID,
		arg.InvitedBy,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.AccessExpiresAt,
		arg.WorkspaceID,
		arg.Email,
	)
	var i ReinviteWorkspaceInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
		&i.WorkspaceName,
		&i.InvitedByUsername,
	)
	return i, err
}

const rejectWorkspaceInvitation = `-- name: RejectWorkspaceInvitation :one
update workspace_user_invitations set
    status = 'rejected',
    updated_at = now()
where id = $1 and status = 'pending'
returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at
`

func (q *Queries) RejectWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, rejectWorkspaceInvitation, id)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
	)
	return i, err
}

const resendInvitation = `-- name: ResendInvitation :one
update workspace_user_invitations set
    status = 'pending',
    expires_at = $2,
    code_hash = $3,
    updated_at = now()
where id = $1 and status in ('pending', 'expired')
returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at
`

type ResendInvitationParams struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CodeHash  string             `json:"code_hash"`
}

func (q *Queries) ResendInvitation(ctx context.Context, arg ResendInvitationParams) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, resendInvitation, arg.ID, arg.ExpiresAt, arg.CodeHash)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
	)
	return i, err
}

const revokeWorkspaceInvitation = `-- name: RevokeWorkspaceInvitation :one
update workspace_user_invitations set
    status = 'revoked',
    updated_at = now()
where id = $1 and status = 'pending'
returning id, workspace_id, email, role_id, user_id, invited_by, code_hash, status, expires_at, accepted_at, created_at, updated_at, group_id, access_expires_at
`

func (q *Queries) RevokeWorkspaceInvitation(ctx context.Context, id pgtype.UUID) (WorkspaceUserInvitation, error) {
	row := q.db.QueryRow(ctx, revokeWorkspaceInvitation, id)
	var i WorkspaceUserInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.RoleID,
		&i.UserID,
		&i.InvitedBy,
		&i.CodeHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.AccessExpiresAt,
	)
	return i, err
}
