// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_groups.sql

package accessdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultGroup = `-- name: CreateDefaultGroup :one
insert into workspace_groups
    (workspace_id, name, description, is_default)
values
    ($1, $2, $3, true)
returning id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit
`

type CreateDefaultGroupParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) CreateDefaultGroup(ctx context.Context, arg CreateDefaultGroupParams) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, createDefaultGroup, arg.WorkspaceID, arg.Name, arg.Description)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
insert into workspace_groups
    (workspace_id, name, description)
values
    ($1, $2, $3)
returning id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit
`

type CreateGroupParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.WorkspaceID, arg.Name, arg.Description)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
delete from workspace_groups where id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getDefaultGroup = `-- name: GetDefaultGroup :one
select id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit from workspace_groups
where workspace_id = $1 and is_default
`

func (q *Queries) GetDefaultGroup(ctx context.Context, workspaceID pgtype.UUID) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, getDefaultGroup, workspaceID)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
select id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit from workspace_groups
where id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id pgtype.UUID) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const getGroups = `-- name: GetGroups :many
select id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit from workspace_groups
where workspace_id = $1
order by created_at
`

func (q *Queries) GetGroups(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceGroup, error) {
	rows, err := q.db.Query(ctx, getGroups, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceGroup
	for rows.Next() {
		var i WorkspaceGroup
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
			&i.QaEnabled,
			&i.QaQuestionLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
update workspace_groups set 
    name = $2,
    description = $3,
    updated_at = now()
where id = $1
returning id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit
`

type UpdateGroupParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}

const updateGroupQA = `-- name: UpdateGroupQA :one
update workspace_groups set
    qa_enabled = $1,
    qa_question_limit = $2,
    updated_at = now()
where id = $3 and workspace_id = $4
returning id, workspace_id, name, description, created_at, updated_at, is_default, qa_enabled, qa_question_limit
`

type UpdateGroupQAParams struct {
	QaEnabled       bool        `json:"qa_enabled"`
	QaQuestionLimit *int32      `json:"qa_question_limit"`
	ID              pgtype.UUID `json:"id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateGroupQA(ctx context.Context, arg UpdateGroupQAParams) (WorkspaceGroup, error) {
	row := q.db.QueryRow(ctx, updateGroupQA,
		arg.QaEnabled,
		arg.QaQuestionLimit,
		arg.ID,
		arg.WorkspaceID,
	)
	var i WorkspaceGroup
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.QaEnabled,
		&i.QaQuestionLimit,
	)
	return i, err
}
