// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package activitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertActivityLog = `-- name: InsertActivityLog :exec
insert into activity_logs 
    (workspace_id, actor_id, actor_name, actor_role, action, target_type, target_id, target_name, metadata)
values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertActivityLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	ActorName   string      `json:"actor_name"`
	ActorRole   string      `json:"actor_role"`
	Action      string      `json:"action"`
	TargetType  string      `json:"target_type"`
	TargetID    pgtype.UUID `json:"target_id"`
	TargetName  string      `json:"target_name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertActivityLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.ActorName,
		arg.ActorRole,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Metadata,
	)
	return err
}

const insertContentEvent = `-- name: InsertContentEvent :exec
insert into content_events
    (workspace_id, document_id, document_name, version_id, page_no, event_type, duration_ms, actor_id, actor_email)
values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertContentEventParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	DocumentID   pgtype.UUID `json:"document_id"`
	DocumentName string      `json:"document_name"`
	VersionID    pgtype.UUID `json:"version_id"`
	PageNo       *int32      `json:"page_no"`
	EventType    string      `json:"event_type"`
	DurationMs   *int32      `json:"duration_ms"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ActorEmail   string      `json:"actor_email"`
}

func (q *Queries) InsertContentEvent(ctx context.Context, arg InsertContentEventParams) error {
	_, err := q.db.Exec(ctx, insertContentEvent,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.DocumentName,
		arg.VersionID,
		arg.PageNo,
		arg.EventType,
		arg.DurationMs,
		arg.ActorID,
		arg.ActorEmail,
	)
	return err
}

const listActivityLogs = `-- name: ListActivityLogs :many
select id, workspace_id, actor_id, actor_name, actor_role, action, target_type, target_id, target_name, metadata, created_at from activity_logs
where
    workspace_id = $1
    and ($2::timestamptz is null
        or (created_at, id) < ($2::timestamptz, $3::uuid))
    and ($4::timestamptz is null or created_at >= $4)
    and ($5::timestamptz is null or created_at <= $5)
    and ($6::uuid is null or actor_id = $6)
    and ($7::text is null or action = $7)
order by created_at desc, id desc
limit $8
`

type ListActivityLogsParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	FromTime        pgtype.Timestamptz `json:"from_time"`
	ToTime          pgtype.Timestamptz `json:"to_time"`
	ActorID         pgtype.UUID        `json:"actor_id"`
	Action          *string            `json:"action"`
	PageSize        int32              `json:"page_size"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivityLogs,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.FromTime,
		arg.ToTime,
		arg.ActorID,
		arg.Action,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityLog
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
