// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package activitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentForEvent = `-- name: GetDocumentForEvent :one
select id, workspace_id, name from documents
where id = $1 and deleted_at is null
`

type GetDocumentForEventRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetDocumentForEvent(ctx context.Context, id pgtype.UUID) (GetDocumentForEventRow, error) {
	row := q.db.QueryRow(ctx, getDocumentForEvent, id)
	var i GetDocumentForEventRow
	err := row.Scan(&i.ID, &i.WorkspaceID, &i.Name)
	return i, err
}

const insertActivityLog = `-- name: InsertActivityLog :exec
insert into activity_logs 
    (workspace_id, actor_id, actor_name, actor_role, action, target_type, target_id, target_name, metadata)
values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertActivityLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	ActorName   string      `json:"actor_name"`
	ActorRole   string      `json:"actor_role"`
	Action      string      `json:"action"`
	TargetType  string      `json:"target_type"`
	TargetID    pgtype.UUID `json:"target_id"`
	TargetName  string      `json:"target_name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertActivityLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.ActorName,
		arg.ActorRole,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Metadata,
	)
	return err
}

const insertContentEvent = `-- name: InsertContentEvent :exec
insert into content_events
    (workspace_id, document_id, document_name, version_id, page_no, event_type, duration_ms, actor_id, actor_email)
values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertContentEventParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	DocumentID   pgtype.UUID `json:"document_id"`
	DocumentName string      `json:"document_name"`
	VersionID    pgtype.UUID `json:"version_id"`
	PageNo       *int32      `json:"page_no"`
	EventType    string      `json:"event_type"`
	DurationMs   *int32      `json:"duration_ms"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ActorEmail   string      `json:"actor_email"`
}

func (q *Queries) InsertContentEvent(ctx context.Context, arg InsertContentEventParams) error {
	_, err := q.db.Exec(ctx, insertContentEvent,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.DocumentName,
		arg.VersionID,
		arg.PageNo,
		arg.EventType,
		arg.DurationMs,
		arg.ActorID,
		arg.ActorEmail,
	)
	return err
}

const listActivityLogs = `-- name: ListActivityLogs :many
select
    a.id, a.workspace_id, a.actor_id, a.actor_name, a.actor_role, a.action, a.target_type, a.target_id, a.target_name, a.metadata, a.created_at,
    coalesce(d.id, dv.id) as link_document_id,
    coalesce(d.folder_id, dv.folder_id, f.id) as link_folder_id,
    qn.id as link_question_id
from activity_logs a
left join documents d
    on a.target_type = 'document' and d.id = a.target_id and d.deleted_at is null
left join document_versions v
    on a.target_type = 'version' and v.id = a.target_id
left join documents dv
    on dv.id = v.document_id and dv.deleted_at is null
left join folders f
    on a.target_type = 'folder' and f.id = a.target_id and f.deleted_at is null
left join questions qn
    on a.target_type = 'question' and qn.id = a.target_id
where
    a.workspace_id = $1
    and ($2::timestamptz is null
        or (a.created_at, a.id) < ($2::timestamptz, $3::uuid))
    and ($4::timestamptz is null or a.created_at >= $4)
    and ($5::timestamptz is null or a.created_at <= $5)
    and ($6::uuid is null or a.actor_id = $6)
    and ($7::text is null or a.action = $7)
order by a.created_at desc, a.id desc
limit $8
`

type ListActivityLogsParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	FromTime        pgtype.Timestamptz `json:"from_time"`
	ToTime          pgtype.Timestamptz `json:"to_time"`
	ActorID         pgtype.UUID        `json:"actor_id"`
	Action          *string            `json:"action"`
	PageSize        int32              `json:"page_size"`
}

type ListActivityLogsRow struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	ActorName      string             `json:"actor_name"`
	ActorRole      string             `json:"actor_role"`
	Action         string             `json:"action"`
	TargetType     string             `json:"target_type"`
	TargetID       pgtype.UUID        `json:"target_id"`
	TargetName     string             `json:"target_name"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LinkDocumentID pgtype.UUID        `json:"link_document_id"`
	LinkFolderID   pgtype.UUID        `json:"link_folder_id"`
	LinkQuestionID pgtype.UUID        `json:"link_question_id"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogs,
		arg.WorkspaceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.FromTime,
		arg.ToTime,
		arg.ActorID,
		arg.Action,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityLogsRow
	for rows.Next() {
		var i ListActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.TargetName,
			&i.Metadata,
			&i.CreatedAt,
			&i.LinkDocumentID,
			&i.LinkFolderID,
			&i.LinkQuestionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentReaders = `-- name: ListDocumentReaders :many
select
    ce.actor_id,
    coalesce(u.username, '')::text as actor_name,
    max(ce.actor_email)::text as actor_email,
    (count(distinct date_bin('5 minutes', ce.created_at, timestamptz 'epoch'))
        filter (where ce.event_type = 'view_page')
    )::bigint as opens,
    (count(distinct ce.page_no) filter (where ce.event_type = 'view_page'))::bigint as pages_seen,
    coalesce(sum(ce.duration_ms) filter (where ce.event_type = 'page_duration'), 0)::bigint as read_ms,
    max(ce.created_at)::timestamptz as last_read_at
from content_events ce
left join users u on u.id = ce.actor_id
where ce.workspace_id = $1
    and ce.document_id = $2
group by ce.actor_id, u.username
order by read_ms desc, last_read_at desc
`

type ListDocumentReadersParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DocumentID  pgtype.UUID `json:"document_id"`
}

type ListDocumentReadersRow struct {
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorName  string             `json:"actor_name"`
	ActorEmail string             `json:"actor_email"`
	Opens      int64              `json:"opens"`
	PagesSeen  int64              `json:"pages_seen"`
	ReadMs     int64              `json:"read_ms"`
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
}

func (q *Queries) ListDocumentReaders(ctx context.Context, arg ListDocumentReadersParams) ([]ListDocumentReadersRow, error) {
	rows, err := q.db.Query(ctx, listDocumentReaders, arg.WorkspaceID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentReadersRow
	for rows.Next() {
		var i ListDocumentReadersRow
		if err := rows.Scan(
			&i.ActorID,
			&i.ActorName,
			&i.ActorEmail,
			&i.Opens,
			&i.PagesSeen,
			&i.ReadMs,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEngagementBreakdown = `-- name: ListEngagementBreakdown :many
select
    ce.actor_id,
    coalesce(u.username, '')::text as actor_name,
    max(ce.actor_email)::text as actor_email,
    ce.page_no,
    (count(distinct date_bin('5 minutes', ce.created_at, timestamptz 'epoch'))
        filter (where ce.event_type = 'view_page')
    )::bigint as opens,
    coalesce(sum(ce.duration_ms) filter (where ce.event_type = 'page_duration'), 0)::bigint as read_ms
from content_events ce
left join users u on u.id = ce.actor_id
where ce.workspace_id = $1
    and ce.document_id = $2
    and ce.page_no is not null
group by ce.actor_id, u.username, ce.page_no
order by actor_name, ce.actor_id, ce.page_no
`

type ListEngagementBreakdownParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DocumentID  pgtype.UUID `json:"document_id"`
}

type ListEngagementBreakdownRow struct {
	ActorID    pgtype.UUID `json:"actor_id"`
	ActorName  string      `json:"actor_name"`
	ActorEmail string      `json:"actor_email"`
	PageNo     *int32      `json:"page_no"`
	Opens      int64       `json:"opens"`
	ReadMs     int64       `json:"read_ms"`
}

func (q *Queries) ListEngagementBreakdown(ctx context.Context, arg ListEngagementBreakdownParams) ([]ListEngagementBreakdownRow, error) {
	rows, err := q.db.Query(ctx, listEngagementBreakdown, arg.WorkspaceID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEngagementBreakdownRow
	for rows.Next() {
		var i ListEngagementBreakdownRow
		if err := rows.Scan(
			&i.ActorID,
			&i.ActorName,
			&i.ActorEmail,
			&i.PageNo,
			&i.Opens,
			&i.ReadMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReaderPages = `-- name: ListReaderPages :many
select
    page_no,
    (count(distinct date_bin('5 minutes', created_at, timestamptz 'epoch'))
        filter (where event_type = 'view_page')
    )::bigint as opens,
    coalesce(sum(duration_ms) filter (where event_type = 'page_duration'), 0)::bigint as read_ms
from content_events
where workspace_id = $1
    and document_id = $2
    and actor_id = $3
    and page_no is not null
group by page_no
order by page_no
`

type ListReaderPagesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DocumentID  pgtype.UUID `json:"document_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
}

type ListReaderPagesRow struct {
	PageNo *int32 `json:"page_no"`
	Opens  int64  `json:"opens"`
	ReadMs int64  `json:"read_ms"`
}

func (q *Queries) ListReaderPages(ctx context.Context, arg ListReaderPagesParams) ([]ListReaderPagesRow, error) {
	rows, err := q.db.Query(ctx, listReaderPages, arg.WorkspaceID, arg.DocumentID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReaderPagesRow
	for rows.Next() {
		var i ListReaderPagesRow
		if err := rows.Scan(&i.PageNo, &i.Opens, &i.ReadMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
