// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package activitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertActivityLog = `-- name: InsertActivityLog :exec
insert into activity_logs 
    (workspace_id, actor_id, actor_name, actor_role, action, target_type, target_id, target_name, metadata)
values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertActivityLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	ActorName   string      `json:"actor_name"`
	ActorRole   string      `json:"actor_role"`
	Action      string      `json:"action"`
	TargetType  string      `json:"target_type"`
	TargetID    pgtype.UUID `json:"target_id"`
	TargetName  string      `json:"target_name"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertActivityLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.ActorName,
		arg.ActorRole,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.TargetName,
		arg.Metadata,
	)
	return err
}

const insertContentEvent = `-- name: InsertContentEvent :exec
insert into content_events
    (workspace_id, document_id, document_name, version_id, page_no, event_type, duration_ms, actor_id, actor_email)
values
    ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertContentEventParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	DocumentID   pgtype.UUID `json:"document_id"`
	DocumentName string      `json:"document_name"`
	VersionID    pgtype.UUID `json:"version_id"`
	PageNo       *int32      `json:"page_no"`
	EventType    string      `json:"event_type"`
	DurationMs   *int32      `json:"duration_ms"`
	ActorID      pgtype.UUID `json:"actor_id"`
	ActorEmail   string      `json:"actor_email"`
}

func (q *Queries) InsertContentEvent(ctx context.Context, arg InsertContentEventParams) error {
	_, err := q.db.Exec(ctx, insertContentEvent,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.DocumentName,
		arg.VersionID,
		arg.PageNo,
		arg.EventType,
		arg.DurationMs,
		arg.ActorID,
		arg.ActorEmail,
	)
	return err
}
