// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package activitydb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	ActorName   string             `json:"actor_name"`
	ActorRole   string             `json:"actor_role"`
	Action      string             `json:"action"`
	TargetType  string             `json:"target_type"`
	TargetID    pgtype.UUID        `json:"target_id"`
	TargetName  string             `json:"target_name"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ContentEvent struct {
	ID           int64              `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	DocumentName string             `json:"document_name"`
	VersionID    pgtype.UUID        `json:"version_id"`
	PageNo       *int32             `json:"page_no"`
	EventType    string             `json:"event_type"`
	DurationMs   *int32             `json:"duration_ms"`
	ActorID      pgtype.UUID        `json:"actor_id"`
	ActorEmail   string             `json:"actor_email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	FolderID            pgtype.UUID        `json:"folder_id"`
	Name                string             `json:"name"`
	CurrentVersionID    pgtype.UUID        `json:"current_version_id"`
	UploadedBy          pgtype.UUID        `json:"uploaded_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Position            int32              `json:"position"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	DeletedRootFolderID pgtype.UUID        `json:"deleted_root_folder_id"`
}

type DocumentVersion struct {
	ID                pgtype.UUID        `json:"id"`
	DocumentID        pgtype.UUID        `json:"document_id"`
	VersionNo         int32              `json:"version_no"`
	Mime              string             `json:"mime"`
	Size              int64              `json:"size"`
	StorageKey        string             `json:"storage_key"`
	UploadedBy        pgtype.UUID        `json:"uploaded_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RenditionKey      *string            `json:"rendition_key"`
	PageCount         *int32             `json:"page_count"`
	RenditionError    *string            `json:"rendition_error"`
	RenditionFailedAt pgtype.Timestamptz `json:"rendition_failed_at"`
}

type Folder struct {
	ID                  pgtype.UUID        `json:"id"`
	WorkspaceID         pgtype.UUID        `json:"workspace_id"`
	ParentID            pgtype.UUID        `json:"parent_id"`
	Name                string             `json:"name"`
	Position            int32              `json:"position"`
	CreatedBy           pgtype.UUID        `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	IsDefault           bool               `json:"is_default"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy           pgtype.UUID        `json:"deleted_by"`
	DeletedRootFolderID pgtype.UUID        `json:"deleted_root_folder_id"`
}

type FolderAccess struct {
	FolderID            pgtype.UUID        `json:"folder_id"`
	GroupID             pgtype.UUID        `json:"group_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CanView             bool               `json:"can_view"`
	CanDownload         bool               `json:"can_download"`
	CanWatermark        bool               `json:"can_watermark"`
	CanDownloadOriginal bool               `json:"can_download_original"`
	CanShare            bool               `json:"can_share"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	Username        *string            `json:"username"`
	PasswordHash    *string            `json:"password_hash"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Provider    string             `json:"provider"`
	ProviderUid string             `json:"provider_uid"`
	Email       *string            `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UserToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceGroup struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsDefault   bool               `json:"is_default"`
}

type WorkspaceGroupMember struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	MemberID  pgtype.UUID        `json:"member_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceRole struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Permissions []string           `json:"permissions"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceUserInvitation struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	RoleID      pgtype.UUID        `json:"role_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	CodeHash    string             `json:"code_hash"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
