// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package activitydb

import (
	"context"
)

type Querier interface {
	InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error
	InsertContentEvent(ctx context.Context, arg InsertContentEventParams) error
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error)
}

var _ Querier = (*Queries)(nil)
