// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package activitydb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetDocumentForEvent(ctx context.Context, id pgtype.UUID) (GetDocumentForEventRow, error)
	InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error
	InsertContentEvent(ctx context.Context, arg InsertContentEventParams) error
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ActivityLog, error)
	ListDocumentReaders(ctx context.Context, arg ListDocumentReadersParams) ([]ListDocumentReadersRow, error)
	ListEngagementBreakdown(ctx context.Context, arg ListEngagementBreakdownParams) ([]ListEngagementBreakdownRow, error)
	ListReaderPages(ctx context.Context, arg ListReaderPagesParams) ([]ListReaderPagesRow, error)
}

var _ Querier = (*Queries)(nil)
