// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archive.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingArchives = `-- name: CountPendingArchives :one
select count(*)::int from workspace_archives
where workspace_id = $1 and status = 'pending'
`

func (q *Queries) CountPendingArchives(ctx context.Context, workspaceID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingArchives, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createArchive = `-- name: CreateArchive :one
insert into workspace_archives
    (workspace_id, requested_by, requested_by_name, expires_at)
values
    ($1, $2, $3, $4)
returning id, workspace_id, requested_by, requested_by_name, status, object_key, size_bytes, checksum_sha256, document_count, missing_count, error, created_at, completed_at, expires_at
`

type CreateArchiveParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	RequestedBy     pgtype.UUID        `json:"requested_by"`
	RequestedByName string             `json:"requested_by_name"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateArchive(ctx context.Context, arg CreateArchiveParams) (WorkspaceArchive, error) {
	row := q.db.QueryRow(ctx, createArchive,
		arg.WorkspaceID,
		arg.RequestedBy,
		arg.RequestedByName,
		arg.ExpiresAt,
	)
	var i WorkspaceArchive
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.RequestedByName,
		&i.Status,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DocumentCount,
		&i.MissingCount,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteArchive = `-- name: DeleteArchive :exec
delete from workspace_archives
where id = $1 and workspace_id = $2
`

type DeleteArchiveParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteArchive(ctx context.Context, arg DeleteArchiveParams) error {
	_, err := q.db.Exec(ctx, deleteArchive, arg.ID, arg.WorkspaceID)
	return err
}

const getArchive = `-- name: GetArchive :one
select id, workspace_id, requested_by, requested_by_name, status, object_key, size_bytes, checksum_sha256, document_count, missing_count, error, created_at, completed_at, expires_at from workspace_archives
where id = $1 and workspace_id = $2
`

type GetArchiveParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetArchive(ctx context.Context, arg GetArchiveParams) (WorkspaceArchive, error) {
	row := q.db.QueryRow(ctx, getArchive, arg.ID, arg.WorkspaceID)
	var i WorkspaceArchive
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RequestedBy,
		&i.RequestedByName,
		&i.Status,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.DocumentCount,
		&i.MissingCount,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getWorkspaceSlugForArchive = `-- name: GetWorkspaceSlugForArchive :one
select slug from workspaces where id = $1
`

func (q *Queries) GetWorkspaceSlugForArchive(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceSlugForArchive, id)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const listArchiveDocuments = `-- name: ListArchiveDocuments :many
select
    d.id,
    d.folder_id,
    d.name,
    d.position,
    v.id as version_id,
    v.version_no,
    v.mime,
    v.size,
    v.rendition_key,
    v.page_count,
    v.rendition_failed_at,
    coalesce(u.username, '')::text as uploaded_by_name,
    v.created_at as version_created_at
from documents d
join document_versions v on v.id = d.current_version_id
left join users u on u.id = v.uploaded_by
where d.workspace_id = $1 and d.deleted_at is null
order by d.folder_id, d.position, d.name, d.created_at
`

type ListArchiveDocumentsRow struct {
	ID                pgtype.UUID        `json:"id"`
	FolderID          pgtype.UUID        `json:"folder_id"`
	Name              string             `json:"name"`
	Position          int32              `json:"position"`
	VersionID         pgtype.UUID        `json:"version_id"`
	VersionNo         int32              `json:"version_no"`
	Mime              string             `json:"mime"`
	Size              int64              `json:"size"`
	RenditionKey      *string            `json:"rendition_key"`
	PageCount         *int32             `json:"page_count"`
	RenditionFailedAt pgtype.Timestamptz `json:"rendition_failed_at"`
	UploadedByName    string             `json:"uploaded_by_name"`
	VersionCreatedAt  pgtype.Timestamptz `json:"version_created_at"`
}

func (q *Queries) ListArchiveDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]ListArchiveDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listArchiveDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveDocumentsRow
	for rows.Next() {
		var i ListArchiveDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FolderID,
			&i.Name,
			&i.Position,
			&i.VersionID,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
			&i.RenditionKey,
			&i.PageCount,
			&i.RenditionFailedAt,
			&i.UploadedByName,
			&i.VersionCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveFolders = `-- name: ListArchiveFolders :many
select id, parent_id, name, position, is_default
from folders
where workspace_id = $1 and deleted_at is null
order by parent_id nulls first, position, created_at
`

type ListArchiveFoldersRow struct {
	ID        pgtype.UUID `json:"id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Position  int32       `json:"position"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) ListArchiveFolders(ctx context.Context, workspaceID pgtype.UUID) ([]ListArchiveFoldersRow, error) {
	rows, err := q.db.Query(ctx, listArchiveFolders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveFoldersRow
	for rows.Next() {
		var i ListArchiveFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchiveMembers = `-- name: ListArchiveMembers :many
select
    coalesce(u.username, '')::text as username,
    coalesce(u.email, '')::text as email,
    coalesce(r.name, '')::text as role_name,
    m.status,
    m.created_at,
    coalesce(
        array_agg(g.name order by g.name) filter (where g.name is not null),
        '{}'
    )::text[] as group_names
from workspace_members m
left join workspace_roles r on r.id = m.role_id
left join users u on u.id = m.user_id
left join workspace_group_members gm on gm.member_id = m.id
left join workspace_groups g on g.id = gm.group_id
where m.workspace_id = $1
group by m.id, u.username, u.email, r.name
order by r.name, u.username
`

type ListArchiveMembersRow struct {
	Username   string             `json:"username"`
	Email      string             `json:"email"`
	RoleName   string             `json:"role_name"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	GroupNames []string           `json:"group_names"`
}

func (q *Queries) ListArchiveMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListArchiveMembersRow, error) {
	rows, err := q.db.Query(ctx, listArchiveMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArchiveMembersRow
	for rows.Next() {
		var i ListArchiveMembersRow
		if err := rows.Scan(
			&i.Username,
			&i.Email,
			&i.RoleName,
			&i.Status,
			&i.CreatedAt,
			&i.GroupNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchives = `-- name: ListArchives :many
select id, workspace_id, requested_by, requested_by_name, status, object_key, size_bytes, checksum_sha256, document_count, missing_count, error, created_at, completed_at, expires_at from workspace_archives
where workspace_id = $1
order by created_at desc
`

func (q *Queries) ListArchives(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceArchive, error) {
	rows, err := q.db.Query(ctx, listArchives, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceArchive
	for rows.Next() {
		var i WorkspaceArchive
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RequestedBy,
			&i.RequestedByName,
			&i.Status,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.DocumentCount,
			&i.MissingCount,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredArchives = `-- name: ListExpiredArchives :many
select id, workspace_id, object_key from workspace_archives
where expires_at < now()
`

type ListExpiredArchivesRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ObjectKey   string      `json:"object_key"`
}

func (q *Queries) ListExpiredArchives(ctx context.Context) ([]ListExpiredArchivesRow, error) {
	rows, err := q.db.Query(ctx, listExpiredArchives)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredArchivesRow
	for rows.Next() {
		var i ListExpiredArchivesRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderAccessMatrix = `-- name: ListFolderAccessMatrix :many
with recursive granted as (
    select
        f.id as folder_id,
        f.parent_id,
        fa.group_id,
        fa.can_view,
        fa.can_download,
        fa.can_watermark,
        fa.can_download_original,
        f.id as source_folder_id
    from folders f
    join folder_access fa on fa.folder_id = f.id
    where f.workspace_id = $1 and f.deleted_at is null

    union all

    select
        c.id,
        c.parent_id,
        g.group_id,
        g.can_view,
        g.can_download,
        g.can_watermark,
        g.can_download_original,
        g.source_folder_id
    from folders c
    join granted g on c.parent_id = g.folder_id
    where c.deleted_at is null
      and not exists (
        select 1
        from folder_access fa2
        where fa2.folder_id = c.id and fa2.group_id = g.group_id
      )
)
select
    g.folder_id,
    g.group_id,
    wg.name as group_name,
    g.can_view,
    g.can_download,
    g.can_watermark,
    g.can_download_original,
    g.source_folder_id
from granted g
join workspace_groups wg on wg.id = g.group_id
order by wg.name, g.folder_id
`

type ListFolderAccessMatrixRow struct {
	FolderID            pgtype.UUID `json:"folder_id"`
	GroupID             pgtype.UUID `json:"group_id"`
	GroupName           string      `json:"group_name"`
	CanView             bool        `json:"can_view"`
	CanDownload         bool        `json:"can_download"`
	CanWatermark        bool        `json:"can_watermark"`
	CanDownloadOriginal bool        `json:"can_download_original"`
	SourceFolderID      pgtype.UUID `json:"source_folder_id"`
}

func (q *Queries) ListFolderAccessMatrix(ctx context.Context, workspaceID pgtype.UUID) ([]ListFolderAccessMatrixRow, error) {
	rows, err := q.db.Query(ctx, listFolderAccessMatrix, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolderAccessMatrixRow
	for rows.Next() {
		var i ListFolderAccessMatrixRow
		if err := rows.Scan(
			&i.FolderID,
			&i.GroupID,
			&i.GroupName,
			&i.CanView,
			&i.CanDownload,
			&i.CanWatermark,
			&i.CanDownloadOriginal,
			&i.SourceFolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingArchives = `-- name: ListStalePendingArchives :many
select id, workspace_id, object_key from workspace_archives
where status = 'pending' and created_at < $1
`

type ListStalePendingArchivesRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ObjectKey   string      `json:"object_key"`
}

func (q *Queries) ListStalePendingArchives(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListStalePendingArchivesRow, error) {
	rows, err := q.db.Query(ctx, listStalePendingArchives, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStalePendingArchivesRow
	for rows.Next() {
		var i ListStalePendingArchivesRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.ObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markArchiveFailed = `-- name: MarkArchiveFailed :exec
update workspace_archives set
    status = 'failed',
    error = $1,
    completed_at = now()
where id = $2 and status = 'pending'
`

type MarkArchiveFailedParams struct {
	Error string      `json:"error"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) MarkArchiveFailed(ctx context.Context, arg MarkArchiveFailedParams) error {
	_, err := q.db.Exec(ctx, markArchiveFailed, arg.Error, arg.ID)
	return err
}

const markArchiveReady = `-- name: MarkArchiveReady :exec
update workspace_archives set
    status = 'ready',
    size_bytes = $1,
    checksum_sha256 = $2,
    document_count = $3,
    missing_count = $4,
    completed_at = now()
where id = $5 and status = 'pending'
`

type MarkArchiveReadyParams struct {
	SizeBytes      int64       `json:"size_bytes"`
	ChecksumSha256 string      `json:"checksum_sha256"`
	DocumentCount  int32       `json:"document_count"`
	MissingCount   int32       `json:"missing_count"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) MarkArchiveReady(ctx context.Context, arg MarkArchiveReadyParams) error {
	_, err := q.db.Exec(ctx, markArchiveReady,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.DocumentCount,
		arg.MissingCount,
		arg.ID,
	)
	return err
}

const setArchiveObjectKey = `-- name: SetArchiveObjectKey :exec
update workspace_archives set object_key = $1
where id = $2
`

type SetArchiveObjectKeyParams struct {
	ObjectKey string      `json:"object_key"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetArchiveObjectKey(ctx context.Context, arg SetArchiveObjectKeyParams) error {
	_, err := q.db.Exec(ctx, setArchiveObjectKey, arg.ObjectKey, arg.ID)
	return err
}
