// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearVersionRenditionFailure = `-- name: ClearVersionRenditionFailure :exec
update document_versions
set rendition_error = null,
    rendition_failed_at = null
where id = $1
`

func (q *Queries) ClearVersionRenditionFailure(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearVersionRenditionFailure, id)
	return err
}

const createDocument = `-- name: CreateDocument :one
insert into documents 
    (workspace_id, folder_id, name, position, uploaded_by)
values
    ($1, $2, $3, $4, $5)
returning id, workspace_id, folder_id, name, current_version_id, uploaded_by, created_at, updated_at, position, deleted_at, deleted_by, deleted_root_folder_id, staged_version_id
`

type CreateDocumentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.WorkspaceID,
		arg.FolderID,
		arg.Name,
		arg.Position,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
		&i.CurrentVersionID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
		&i.StagedVersionID,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
insert into document_versions
    (document_id, version_no, mime, size, storage_key, uploaded_by)
values 
    ($1, $2, $3, $4, $5, $6)
returning id, document_id, version_no, mime, size, storage_key, uploaded_by, created_at, rendition_key, page_count, rendition_error, rendition_failed_at, text_extracted_at, text_error, text_failed_at
`

type CreateDocumentVersionParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	VersionNo  int32       `json:"version_no"`
	Mime       string      `json:"mime"`
	Size       int64       `json:"size"`
	StorageKey string      `json:"storage_key"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.DocumentID,
		arg.VersionNo,
		arg.Mime,
		arg.Size,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNo,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.RenditionKey,
		&i.PageCount,
		&i.RenditionError,
		&i.RenditionFailedAt,
		&i.TextExtractedAt,
		&i.TextError,
		&i.TextFailedAt,
	)
	return i, err
}

const getCurrentVersion = `-- name: GetCurrentVersion :one
select v.id, v.document_id, v.version_no, v.mime, v.size, v.storage_key, v.uploaded_by, v.created_at, v.rendition_key, v.page_count, v.rendition_error, v.rendition_failed_at, v.text_extracted_at, v.text_error, v.text_failed_at from document_versions v 
join documents d on d.current_version_id = v.id
where d.id = $1
`

func (q *Queries) GetCurrentVersion(ctx context.Context, id pgtype.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentVersion, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNo,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.RenditionKey,
		&i.PageCount,
		&i.RenditionError,
		&i.RenditionFailedAt,
		&i.TextExtractedAt,
		&i.TextError,
		&i.TextFailedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
select id, workspace_id, folder_id, name, current_version_id, uploaded_by, created_at, updated_at, position, deleted_at, deleted_by, deleted_root_folder_id, staged_version_id from documents where id = $1 and deleted_at is null
`

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
		&i.CurrentVersionID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
		&i.StagedVersionID,
	)
	return i, err
}

const getDocumentByNameInFolder = `-- name: GetDocumentByNameInFolder :one
select id, workspace_id, folder_id, name, current_version_id, uploaded_by, created_at, updated_at, position, deleted_at, deleted_by, deleted_root_folder_id, staged_version_id from documents where folder_id = $1 and name = $2 and deleted_at is null
`

type GetDocumentByNameInFolderParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Name     string      `json:"name"`
}

func (q *Queries) GetDocumentByNameInFolder(ctx context.Context, arg GetDocumentByNameInFolderParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByNameInFolder, arg.FolderID, arg.Name)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
		&i.CurrentVersionID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
		&i.StagedVersionID,
	)
	return i, err
}

const getMaxPosition = `-- name: GetMaxPosition :one
select coalesce(max(position), -1)::int as max_position
from documents
where folder_id = $1 and deleted_at is null
`

func (q *Queries) GetMaxPosition(ctx context.Context, folderID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPosition, folderID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const getNextVersionNo = `-- name: GetNextVersionNo :one
select coalesce(max(version_no),0)::int + 1 as next_no
from document_versions where document_id = $1
`

func (q *Queries) GetNextVersionNo(ctx context.Context, documentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextVersionNo, documentID)
	var next_no int32
	err := row.Scan(&next_no)
	return next_no, err
}

const getTrashedDocumentByID = `-- name: GetTrashedDocumentByID :one
select id, workspace_id, folder_id, name, current_version_id, uploaded_by, created_at, updated_at, position, deleted_at, deleted_by, deleted_root_folder_id, staged_version_id from documents where id = $1 and deleted_at is not null
`

func (q *Queries) GetTrashedDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getTrashedDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.FolderID,
		&i.Name,
		&i.CurrentVersionID,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
		&i.StagedVersionID,
	)
	return i, err
}

const getVersionByID = `-- name: GetVersionByID :one
select id, document_id, version_no, mime, size, storage_key, uploaded_by, created_at, rendition_key, page_count, rendition_error, rendition_failed_at, text_extracted_at, text_error, text_failed_at from document_versions where id = $1
`

func (q *Queries) GetVersionByID(ctx context.Context, id pgtype.UUID) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByID, id)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.VersionNo,
		&i.Mime,
		&i.Size,
		&i.StorageKey,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.RenditionKey,
		&i.PageCount,
		&i.RenditionError,
		&i.RenditionFailedAt,
		&i.TextExtractedAt,
		&i.TextError,
		&i.TextFailedAt,
	)
	return i, err
}

const listDocumentsByFolder = `-- name: ListDocumentsByFolder :many
select
    d.id,
    d.name,
    d.folder_id,
    d.current_version_id,
    d.uploaded_by,
    d.created_at,
    d.updated_at,
    v.version_no,
    v.mime,
    v.size,
    v.rendition_key,
    v.rendition_failed_at,
    sv.id as staged_version_id,
    sv.version_no as staged_version_no,
    sv.rendition_key as staged_rendition_key,
    sv.rendition_failed_at as staged_rendition_failed_at,
    (select count(*) from document_versions dv where dv.document_id = d.id)::int as version_count
from documents d
join document_versions v on v.id = d.current_version_id
left join document_versions sv on sv.id = d.staged_version_id
where d.folder_id = $1 and d.deleted_at is null
order by d.position, d.name, d.created_at
`

type ListDocumentsByFolderRow struct {
	ID                      pgtype.UUID        `json:"id"`
	Name                    string             `json:"name"`
	FolderID                pgtype.UUID        `json:"folder_id"`
	CurrentVersionID        pgtype.UUID        `json:"current_version_id"`
	UploadedBy              pgtype.UUID        `json:"uploaded_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	VersionNo               int32              `json:"version_no"`
	Mime                    string             `json:"mime"`
	Size                    int64              `json:"size"`
	RenditionKey            *string            `json:"rendition_key"`
	RenditionFailedAt       pgtype.Timestamptz `json:"rendition_failed_at"`
	StagedVersionID         pgtype.UUID        `json:"staged_version_id"`
	StagedVersionNo         *int32             `json:"staged_version_no"`
	StagedRenditionKey      *string            `json:"staged_rendition_key"`
	StagedRenditionFailedAt pgtype.Timestamptz `json:"staged_rendition_failed_at"`
	VersionCount            int32              `json:"version_count"`
}

func (q *Queries) ListDocumentsByFolder(ctx context.Context, folderID pgtype.UUID) ([]ListDocumentsByFolderRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByFolderRow
	for rows.Next() {
		var i ListDocumentsByFolderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.CurrentVersionID,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
			&i.RenditionKey,
			&i.RenditionFailedAt,
			&i.StagedVersionID,
			&i.StagedVersionNo,
			&i.StagedRenditionKey,
			&i.StagedRenditionFailedAt,
			&i.VersionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredTrashDocuments = `-- name: ListExpiredTrashDocuments :many
select id, workspace_id, name from documents
where deleted_at is not null
and deleted_root_folder_id is null
and deleted_at < $1
`

type ListExpiredTrashDocumentsRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) ListExpiredTrashDocuments(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListExpiredTrashDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredTrashDocuments, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredTrashDocumentsRow
	for rows.Next() {
		var i ListExpiredTrashDocumentsRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashDocuments = `-- name: ListTrashDocuments :many
select d.id, d.name, d.deleted_at,
    coalesce(u.username, u.email)::text as deleted_by_name,
    v.mime, v.size,
    coalesce(p.name, '')::text as folder_name,
    (p.id is null)::boolean as folder_gone
from documents d
join users u on u.id = d.deleted_by
left join document_versions v on v.id = d.current_version_id
left join folders p on p.id = d.folder_id and p.deleted_at is null
where d.workspace_id = $1
    and d.deleted_at is not null
    and d.deleted_root_folder_id is null
order by d.deleted_at desc
`

type ListTrashDocumentsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
	Mime          *string            `json:"mime"`
	Size          *int64             `json:"size"`
	FolderName    string             `json:"folder_name"`
	FolderGone    bool               `json:"folder_gone"`
}

func (q *Queries) ListTrashDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]ListTrashDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listTrashDocuments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashDocumentsRow
	for rows.Next() {
		var i ListTrashDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.DeletedByName,
			&i.Mime,
			&i.Size,
			&i.FolderName,
			&i.FolderGone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionByDocument = `-- name: ListVersionByDocument :many
select id, document_id, version_no, mime, size, storage_key, uploaded_by, created_at, rendition_key, page_count, rendition_error, rendition_failed_at, text_extracted_at, text_error, text_failed_at from document_versions where document_id = $1 order by version_no desc
`

func (q *Queries) ListVersionByDocument(ctx context.Context, documentID pgtype.UUID) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listVersionByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentVersion
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.RenditionKey,
			&i.PageCount,
			&i.RenditionError,
			&i.RenditionFailedAt,
			&i.TextExtractedAt,
			&i.TextError,
			&i.TextFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsWithUploader = `-- name: ListVersionsWithUploader :many
select
    v.id, v.document_id, v.version_no, v.mime, v.size, v.storage_key, v.uploaded_by, v.created_at, v.rendition_key, v.page_count, v.rendition_error, v.rendition_failed_at, v.text_extracted_at, v.text_error, v.text_failed_at,
    coalesce(u.username, u.email)::text as uploaded_by_name,
    coalesce(d.current_version_id = v.id, false)::bool as is_current,
    coalesce(d.staged_version_id = v.id, false)::bool as is_staged
from document_versions v
join users u on u.id = v.uploaded_by
join documents d on d.id = v.document_id
where v.document_id = $1
order by v.version_no desc
`

type ListVersionsWithUploaderRow struct {
	ID                pgtype.UUID        `json:"id"`
	DocumentID        pgtype.UUID        `json:"document_id"`
	VersionNo         int32              `json:"version_no"`
	Mime              string             `json:"mime"`
	Size              int64              `json:"size"`
	StorageKey        string             `json:"storage_key"`
	UploadedBy        pgtype.UUID        `json:"uploaded_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RenditionKey      *string            `json:"rendition_key"`
	PageCount         *int32             `json:"page_count"`
	RenditionError    *string            `json:"rendition_error"`
	RenditionFailedAt pgtype.Timestamptz `json:"rendition_failed_at"`
	TextExtractedAt   pgtype.Timestamptz `json:"text_extracted_at"`
	TextError         *string            `json:"text_error"`
	TextFailedAt      pgtype.Timestamptz `json:"text_failed_at"`
	UploadedByName    string             `json:"uploaded_by_name"`
	IsCurrent         bool               `json:"is_current"`
	IsStaged          bool               `json:"is_staged"`
}

// `is_current` is the served version, which restore repoints freely, so it is
// not necessarily the highest version_no. current_version_id is nullable.
// `is_staged` marks an upload waiting for its rendition to prove out before it
// is served; at most one version per document carries it.
func (q *Queries) ListVersionsWithUploader(ctx context.Context, documentID pgtype.UUID) ([]ListVersionsWithUploaderRow, error) {
	rows, err := q.db.Query(ctx, listVersionsWithUploader, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionsWithUploaderRow
	for rows.Next() {
		var i ListVersionsWithUploaderRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.RenditionKey,
			&i.PageCount,
			&i.RenditionError,
			&i.RenditionFailedAt,
			&i.TextExtractedAt,
			&i.TextError,
			&i.TextFailedAt,
			&i.UploadedByName,
			&i.IsCurrent,
			&i.IsStaged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveDocument = `-- name: MoveDocument :exec
update documents set folder_id = $2, position = $3, updated_at = now() where id = $1
`

type MoveDocumentParams struct {
	ID       pgtype.UUID `json:"id"`
	FolderID pgtype.UUID `json:"folder_id"`
	Position int32       `json:"position"`
}

func (q *Queries) MoveDocument(ctx context.Context, arg MoveDocumentParams) error {
	_, err := q.db.Exec(ctx, moveDocument, arg.ID, arg.FolderID, arg.Position)
	return err
}

const promoteStagedVersion = `-- name: PromoteStagedVersion :execrows
update documents set
    current_version_id = $1,
    staged_version_id = null,
    updated_at = now()
where id = $2 and staged_version_id = $1
`

type PromoteStagedVersionParams struct {
	VersionID pgtype.UUID `json:"version_id"`
	ID        pgtype.UUID `json:"id"`
}

// The where-guard makes promotion atomic and idempotent: it only fires while
// the document still stages this exact version, so a restore or a newer upload
// that raced the conversion wins and this becomes a no-op.
func (q *Queries) PromoteStagedVersion(ctx context.Context, arg PromoteStagedVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, promoteStagedVersion, arg.VersionID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeDocument = `-- name: PurgeDocument :exec
delete from documents where id = $1
`

func (q *Queries) PurgeDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, purgeDocument, id)
	return err
}

const reindexDocumentSiblings = `-- name: ReindexDocumentSiblings :exec
with ordered as (
    select d.id as document_id,
        (row_number() over (
            order by position,
                    case when d.id = $1 then 0 else 1 end,
                    d.name 
        ))::int - 1 as rn 
    from documents d
    where d.folder_id = $2
    and d.deleted_at is null
)
update documents t
set position = o.rn 
from ordered o 
where t.id = o.document_id and t.position <> o.rn
`

type ReindexDocumentSiblingsParams struct {
	MovedID  pgtype.UUID `json:"moved_id"`
	FolderID pgtype.UUID `json:"folder_id"`
}

func (q *Queries) ReindexDocumentSiblings(ctx context.Context, arg ReindexDocumentSiblingsParams) error {
	_, err := q.db.Exec(ctx, reindexDocumentSiblings, arg.MovedID, arg.FolderID)
	return err
}

const restoreDocument = `-- name: RestoreDocument :exec
update documents set
    deleted_at = null,
    deleted_by = null,
    deleted_root_folder_id = null,
    folder_id = $1,
    name = $2,
    position = $3,
    updated_at = now()
where id = $4
`

type RestoreDocumentParams struct {
	FolderID pgtype.UUID `json:"folder_id"`
	Name     string      `json:"name"`
	Position int32       `json:"position"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) RestoreDocument(ctx context.Context, arg RestoreDocumentParams) error {
	_, err := q.db.Exec(ctx, restoreDocument,
		arg.FolderID,
		arg.Name,
		arg.Position,
		arg.ID,
	)
	return err
}

const restoreDocumentsSweptBy = `-- name: RestoreDocumentsSweptBy :exec
update documents set
    deleted_at = null,
    deleted_by = null,
    deleted_root_folder_id = null,
    updated_at = now()
where deleted_root_folder_id = $1
`

func (q *Queries) RestoreDocumentsSweptBy(ctx context.Context, deletedRootFolderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreDocumentsSweptBy, deletedRootFolderID)
	return err
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
update documents set
    current_version_id = $2,
    staged_version_id = null,
    updated_at = now()
where id = $1
`

type SetCurrentVersionParams struct {
	ID               pgtype.UUID `json:"id"`
	CurrentVersionID pgtype.UUID `json:"current_version_id"`
}

// An explicit pointer set (first upload, restore) supersedes any staging in
// flight: a version left staged after the owner chose another would promote
// itself behind their back the moment its conversion finished.
func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setStagedVersion = `-- name: SetStagedVersion :exec
update documents set
    staged_version_id = $2,
    updated_at = now()
where id = $1
`

type SetStagedVersionParams struct {
	ID              pgtype.UUID `json:"id"`
	StagedVersionID pgtype.UUID `json:"staged_version_id"`
}

func (q *Queries) SetStagedVersion(ctx context.Context, arg SetStagedVersionParams) error {
	_, err := q.db.Exec(ctx, setStagedVersion, arg.ID, arg.StagedVersionID)
	return err
}

const setVersionRendition = `-- name: SetVersionRendition :exec
update document_versions
set rendition_key = $1,
    page_count = $2
where id = $3
`

type SetVersionRenditionParams struct {
	RenditionKey *string     `json:"rendition_key"`
	PageCount    *int32      `json:"page_count"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetVersionRendition(ctx context.Context, arg SetVersionRenditionParams) error {
	_, err := q.db.Exec(ctx, setVersionRendition, arg.RenditionKey, arg.PageCount, arg.ID)
	return err
}

const setVersionRenditionFailure = `-- name: SetVersionRenditionFailure :exec
update document_versions
set rendition_error = $1,
    rendition_failed_at = now()
where id = $2
`

type SetVersionRenditionFailureParams struct {
	RenditionError *string     `json:"rendition_error"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) SetVersionRenditionFailure(ctx context.Context, arg SetVersionRenditionFailureParams) error {
	_, err := q.db.Exec(ctx, setVersionRenditionFailure, arg.RenditionError, arg.ID)
	return err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
update documents set 
    deleted_at = now(),
    deleted_by = $2,
    updated_at = now()
where id = $1
`

type SoftDeleteDocumentParams struct {
	ID        pgtype.UUID `json:"id"`
	DeletedBy pgtype.UUID `json:"deleted_by"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.DeletedBy)
	return err
}
