// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_job.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownloadJob = `-- name: CreateDownloadJob :one
insert into document_download_jobs (
    workspace_id, document_id, version_id, requested_by,
    document_name, version_no, page_count, expires_at
) values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, workspace_id, document_id, version_id, requested_by, document_name, version_no, page_count, status, object_key, size_bytes, error, created_at, completed_at, expires_at
`

type CreateDownloadJobParams struct {
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	VersionID    pgtype.UUID        `json:"version_id"`
	RequestedBy  pgtype.UUID        `json:"requested_by"`
	DocumentName string             `json:"document_name"`
	VersionNo    int32              `json:"version_no"`
	PageCount    int32              `json:"page_count"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDownloadJob(ctx context.Context, arg CreateDownloadJobParams) (DocumentDownloadJob, error) {
	row := q.db.QueryRow(ctx, createDownloadJob,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.VersionID,
		arg.RequestedBy,
		arg.DocumentName,
		arg.VersionNo,
		arg.PageCount,
		arg.ExpiresAt,
	)
	var i DocumentDownloadJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.VersionID,
		&i.RequestedBy,
		&i.DocumentName,
		&i.VersionNo,
		&i.PageCount,
		&i.Status,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteDownloadJob = `-- name: DeleteDownloadJob :exec
delete from document_download_jobs where id = $1
`

func (q *Queries) DeleteDownloadJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDownloadJob, id)
	return err
}

const getDownloadJob = `-- name: GetDownloadJob :one
select id, workspace_id, document_id, version_id, requested_by, document_name, version_no, page_count, status, object_key, size_bytes, error, created_at, completed_at, expires_at from document_download_jobs where id = $1
`

func (q *Queries) GetDownloadJob(ctx context.Context, id pgtype.UUID) (DocumentDownloadJob, error) {
	row := q.db.QueryRow(ctx, getDownloadJob, id)
	var i DocumentDownloadJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.VersionID,
		&i.RequestedBy,
		&i.DocumentName,
		&i.VersionNo,
		&i.PageCount,
		&i.Status,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPendingDownloadJob = `-- name: GetPendingDownloadJob :one
select id, workspace_id, document_id, version_id, requested_by, document_name, version_no, page_count, status, object_key, size_bytes, error, created_at, completed_at, expires_at from document_download_jobs
where workspace_id = $1
  and requested_by = $2
  and version_id = $3
  and status = 'pending'
order by created_at desc
limit 1
`

type GetPendingDownloadJobParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RequestedBy pgtype.UUID `json:"requested_by"`
	VersionID   pgtype.UUID `json:"version_id"`
}

func (q *Queries) GetPendingDownloadJob(ctx context.Context, arg GetPendingDownloadJobParams) (DocumentDownloadJob, error) {
	row := q.db.QueryRow(ctx, getPendingDownloadJob, arg.WorkspaceID, arg.RequestedBy, arg.VersionID)
	var i DocumentDownloadJob
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.VersionID,
		&i.RequestedBy,
		&i.DocumentName,
		&i.VersionNo,
		&i.PageCount,
		&i.Status,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listDownloadJobsForUser = `-- name: ListDownloadJobsForUser :many
select id, workspace_id, document_id, version_id, requested_by, document_name, version_no, page_count, status, object_key, size_bytes, error, created_at, completed_at, expires_at from document_download_jobs
where workspace_id = $1
  and requested_by = $2
  and expires_at > now()
order by created_at desc
limit $3
`

type ListDownloadJobsForUserParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RequestedBy pgtype.UUID `json:"requested_by"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListDownloadJobsForUser(ctx context.Context, arg ListDownloadJobsForUserParams) ([]DocumentDownloadJob, error) {
	rows, err := q.db.Query(ctx, listDownloadJobsForUser, arg.WorkspaceID, arg.RequestedBy, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentDownloadJob
	for rows.Next() {
		var i DocumentDownloadJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocumentID,
			&i.VersionID,
			&i.RequestedBy,
			&i.DocumentName,
			&i.VersionNo,
			&i.PageCount,
			&i.Status,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredDownloadJobs = `-- name: ListExpiredDownloadJobs :many
select id, workspace_id, document_id, version_id, requested_by, document_name, version_no, page_count, status, object_key, size_bytes, error, created_at, completed_at, expires_at from document_download_jobs where expires_at <= now()
`

func (q *Queries) ListExpiredDownloadJobs(ctx context.Context) ([]DocumentDownloadJob, error) {
	rows, err := q.db.Query(ctx, listExpiredDownloadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentDownloadJob
	for rows.Next() {
		var i DocumentDownloadJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocumentID,
			&i.VersionID,
			&i.RequestedBy,
			&i.DocumentName,
			&i.VersionNo,
			&i.PageCount,
			&i.Status,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalePendingDownloadJobs = `-- name: ListStalePendingDownloadJobs :many
select id, workspace_id, document_id, version_id, requested_by, document_name, version_no, page_count, status, object_key, size_bytes, error, created_at, completed_at, expires_at from document_download_jobs
where status = 'pending' and created_at < $1
`

func (q *Queries) ListStalePendingDownloadJobs(ctx context.Context, cutoff pgtype.Timestamptz) ([]DocumentDownloadJob, error) {
	rows, err := q.db.Query(ctx, listStalePendingDownloadJobs, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentDownloadJob
	for rows.Next() {
		var i DocumentDownloadJob
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DocumentID,
			&i.VersionID,
			&i.RequestedBy,
			&i.DocumentName,
			&i.VersionNo,
			&i.PageCount,
			&i.Status,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDownloadJobFailed = `-- name: MarkDownloadJobFailed :exec
update document_download_jobs
set status = 'failed',
    error = $2,
    completed_at = now()
where id = $1 and status = 'pending'
`

type MarkDownloadJobFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error string      `json:"error"`
}

func (q *Queries) MarkDownloadJobFailed(ctx context.Context, arg MarkDownloadJobFailedParams) error {
	_, err := q.db.Exec(ctx, markDownloadJobFailed, arg.ID, arg.Error)
	return err
}

const markDownloadJobReady = `-- name: MarkDownloadJobReady :exec
update document_download_jobs
set status = 'ready',
    object_key = $2,
    size_bytes = $3,
    completed_at = now()
where id = $1 and status = 'pending'
`

type MarkDownloadJobReadyParams struct {
	ID        pgtype.UUID `json:"id"`
	ObjectKey string      `json:"object_key"`
	SizeBytes int64       `json:"size_bytes"`
}

func (q *Queries) MarkDownloadJobReady(ctx context.Context, arg MarkDownloadJobReadyParams) error {
	_, err := q.db.Exec(ctx, markDownloadJobReady, arg.ID, arg.ObjectKey, arg.SizeBytes)
	return err
}
