// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDefaultFolder = `-- name: CreateDefaultFolder :one
insert into folders
    (workspace_id, parent_id, name, position, created_by, is_default)
values
    ($1, null, $2, 0, $3, true)
returning id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id
`

type CreateDefaultFolderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDefaultFolder(ctx context.Context, arg CreateDefaultFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createDefaultFolder, arg.WorkspaceID, arg.Name, arg.CreatedBy)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one
insert into folders
    (workspace_id, parent_id, name, position, created_by)
values
    ($1, $2, $3, $4, $5)
returning id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id
`

type CreateFolderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Position    int32       `json:"position"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Position,
		arg.CreatedBy,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const getDefaultFolder = `-- name: GetDefaultFolder :one
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id from folders
where workspace_id = $1 and is_default = true and deleted_at is null
`

func (q *Queries) GetDefaultFolder(ctx context.Context, workspaceID pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getDefaultFolder, workspaceID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id from folders where id = $1 and deleted_at is null
`

func (q *Queries) GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const getFolderByNameInParent = `-- name: GetFolderByNameInParent :one
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id from folders
where workspace_id = $1
    and parent_id is not distinct from $2
    and name = $3
    and deleted_at is null
`

type GetFolderByNameInParentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetFolderByNameInParent(ctx context.Context, arg GetFolderByNameInParentParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByNameInParent, arg.WorkspaceID, arg.ParentID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const getFoldersByWorkspace = `-- name: GetFoldersByWorkspace :many
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id from folders where workspace_id = $1 and deleted_at is null
order by parent_id nulls first, position, created_at
`

func (q *Queries) GetFoldersByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getFoldersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDefault,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.DeletedRootFolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxPositionInParent = `-- name: GetMaxPositionInParent :one
select coalesce(max(position), -1)::int as max_position
from folders
where workspace_id = $1 and parent_id is not distinct from $2
    and deleted_at is null
`

type GetMaxPositionInParentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) GetMaxPositionInParent(ctx context.Context, arg GetMaxPositionInParentParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPositionInParent, arg.WorkspaceID, arg.ParentID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const getTrashedFolderByID = `-- name: GetTrashedFolderByID :one
select id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id from folders where id = $1 and deleted_at is not null
`

func (q *Queries) GetTrashedFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getTrashedFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const listTrashFolders = `-- name: ListTrashFolders :many
select f.id, f.name, f.deleted_at,
    coalesce(u.username, u.email)::text as deleted_by_name
from folders f
join users u on u.id = f.deleted_by
where f.workspace_id = $1
    and f.deleted_at is not null
    and f.deleted_root_folder_id is null
order by f.deleted_at desc
`

type ListTrashFoldersRow struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	DeletedByName string             `json:"deleted_by_name"`
}

func (q *Queries) ListTrashFolders(ctx context.Context, workspaceID pgtype.UUID) ([]ListTrashFoldersRow, error) {
	rows, err := q.db.Query(ctx, listTrashFolders, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrashFoldersRow
	for rows.Next() {
		var i ListTrashFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeletedAt,
			&i.DeletedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceStructure = `-- name: LockWorkspaceStructure :exec
select pg_advisory_xact_lock(hashtext($1::uuid::text))
`

func (q *Queries) LockWorkspaceStructure(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceStructure, workspaceID)
	return err
}

const moveFolder = `-- name: MoveFolder :exec
update folders set
    parent_id = $2,
    position = $3,
    updated_at = now()
where id = $1
`

type MoveFolderParams struct {
	ID       pgtype.UUID `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
	Position int32       `json:"position"`
}

func (q *Queries) MoveFolder(ctx context.Context, arg MoveFolderParams) error {
	_, err := q.db.Exec(ctx, moveFolder, arg.ID, arg.ParentID, arg.Position)
	return err
}

const reindexFolderSiblings = `-- name: ReindexFolderSiblings :exec
with ordered as (
    select f.id as folder_id,
        (row_number() over (
            order by position,
                    case when f.id = $1 then 0 else 1 end,
                    f.name
        ))::int - 1 as rn
    from folders f
    where f.workspace_id = $2
    and f.parent_id is not distinct from $3
    and f.deleted_at is null
)
update folders t 
set position = o.rn 
from ordered o 
where t.id = o.folder_id and t.position <> o.rn
`

type ReindexFolderSiblingsParams struct {
	MovedID     pgtype.UUID `json:"moved_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ReindexFolderSiblings(ctx context.Context, arg ReindexFolderSiblingsParams) error {
	_, err := q.db.Exec(ctx, reindexFolderSiblings, arg.MovedID, arg.WorkspaceID, arg.ParentID)
	return err
}

const renameFolder = `-- name: RenameFolder :one
update folders set name = $2, updated_at = now() where id = $1 returning id, workspace_id, parent_id, name, position, created_by, created_at, updated_at, is_default, deleted_at, deleted_by, deleted_root_folder_id
`

type RenameFolderParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, renameFolder, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDefault,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.DeletedRootFolderID,
	)
	return i, err
}

const restoreFolderRoot = `-- name: RestoreFolderRoot :exec
update folders set
    deleted_at = null,
    deleted_by = null,
    parent_id = $1,
    name = $2,
    position = $3,
    updated_at = now()
where id = $4
`

type RestoreFolderRootParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Name     string      `json:"name"`
	Position int32       `json:"position"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) RestoreFolderRoot(ctx context.Context, arg RestoreFolderRootParams) error {
	_, err := q.db.Exec(ctx, restoreFolderRoot,
		arg.ParentID,
		arg.Name,
		arg.Position,
		arg.ID,
	)
	return err
}

const restoreFoldersSweptBy = `-- name: RestoreFoldersSweptBy :exec
update folders set  
    deleted_at = null,
    deleted_by = null,
    deleted_root_folder_id = null,
    updated_at = now()
where deleted_root_folder_id = $1
`

func (q *Queries) RestoreFoldersSweptBy(ctx context.Context, deletedRootFolderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreFoldersSweptBy, deletedRootFolderID)
	return err
}

const softDeleteDocumentsForFolderRoot = `-- name: SoftDeleteDocumentsForFolderRoot :exec
update documents d
set deleted_at = now(),
    deleted_by = $1,
    deleted_root_folder_id = $2
from folders f
where d.folder_id = f.id
    and d.deleted_at is null
    and (f.id = $2 or f.deleted_root_folder_id = $2)
`

type SoftDeleteDocumentsForFolderRootParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	FolderID  pgtype.UUID `json:"folder_id"`
}

func (q *Queries) SoftDeleteDocumentsForFolderRoot(ctx context.Context, arg SoftDeleteDocumentsForFolderRootParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocumentsForFolderRoot, arg.DeletedBy, arg.FolderID)
	return err
}

const softDeleteFolderSubtree = `-- name: SoftDeleteFolderSubtree :exec
with recursive subtree as (
    select id from folders
    where id = $2 and deleted_at is null
    union all
    select f.id from folders f
    join subtree s on f.parent_id = s.id
    where f.deleted_at is null
)
update folders f
set deleted_at = now(),
    deleted_by = $1,
    deleted_root_folder_id = case 
        when f.id = $2 then null 
        else $2
    end
from subtree s 
where f.id = s.id
`

type SoftDeleteFolderSubtreeParams struct {
	DeletedBy pgtype.UUID `json:"deleted_by"`
	FolderID  pgtype.UUID `json:"folder_id"`
}

func (q *Queries) SoftDeleteFolderSubtree(ctx context.Context, arg SoftDeleteFolderSubtreeParams) error {
	_, err := q.db.Exec(ctx, softDeleteFolderSubtree, arg.DeletedBy, arg.FolderID)
	return err
}
