// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearVersionRenditionFailure(ctx context.Context, id pgtype.UUID) error
	CreateDefaultFolder(ctx context.Context, arg CreateDefaultFolderParams) (Folder, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	DeleteVersionPageText(ctx context.Context, versionID pgtype.UUID) error
	GetCurrentVersion(ctx context.Context, id pgtype.UUID) (DocumentVersion, error)
	GetDefaultFolder(ctx context.Context, workspaceID pgtype.UUID) (Folder, error)
	GetDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	GetDocumentByNameInFolder(ctx context.Context, arg GetDocumentByNameInFolderParams) (Document, error)
	GetFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetFolderByNameInParent(ctx context.Context, arg GetFolderByNameInParentParams) (Folder, error)
	GetFoldersByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Folder, error)
	GetMaxPosition(ctx context.Context, folderID pgtype.UUID) (int32, error)
	GetMaxPositionInParent(ctx context.Context, arg GetMaxPositionInParentParams) (int32, error)
	GetNextVersionNo(ctx context.Context, documentID pgtype.UUID) (int32, error)
	GetTrashedDocumentByID(ctx context.Context, id pgtype.UUID) (Document, error)
	GetTrashedFolderByID(ctx context.Context, id pgtype.UUID) (Folder, error)
	GetVersionByID(ctx context.Context, id pgtype.UUID) (DocumentVersion, error)
	InsertPageText(ctx context.Context, arg InsertPageTextParams) error
	ListDocumentsByFolder(ctx context.Context, folderID pgtype.UUID) ([]ListDocumentsByFolderRow, error)
	ListExpiredTrashDocuments(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListExpiredTrashDocumentsRow, error)
	ListExpiredTrashFolders(ctx context.Context, cutoff pgtype.Timestamptz) ([]ListExpiredTrashFoldersRow, error)
	ListFolderAccess(ctx context.Context, arg ListFolderAccessParams) ([]ListFolderAccessRow, error)
	ListPendingOCRPages(ctx context.Context, limitCount int32) ([]ListPendingOCRPagesRow, error)
	ListPendingTextExtraction(ctx context.Context, limit int32) ([]ListPendingTextExtractionRow, error)
	ListTrashDocuments(ctx context.Context, workspaceID pgtype.UUID) ([]ListTrashDocumentsRow, error)
	ListTrashFolders(ctx context.Context, workspaceID pgtype.UUID) ([]ListTrashFoldersRow, error)
	ListVersionByDocument(ctx context.Context, documentID pgtype.UUID) ([]DocumentVersion, error)
	ListVersionsSweptByFolder(ctx context.Context, folderID pgtype.UUID) ([]ListVersionsSweptByFolderRow, error)
	// `is_current` is the served version, which restore repoints freely, so it is
	// not necessarily the highest version_no. current_version_id is nullable.
	ListVersionsWithUploader(ctx context.Context, documentID pgtype.UUID) ([]ListVersionsWithUploaderRow, error)
	ListVisibleFolders(ctx context.Context, arg ListVisibleFoldersParams) ([]ListVisibleFoldersRow, error)
	LockWorkspaceStructure(ctx context.Context, workspaceID pgtype.UUID) error
	MoveDocument(ctx context.Context, arg MoveDocumentParams) error
	MoveFolder(ctx context.Context, arg MoveFolderParams) error
	PurgeDocument(ctx context.Context, id pgtype.UUID) error
	PurgeFolder(ctx context.Context, id pgtype.UUID) error
	ReindexDocumentSiblings(ctx context.Context, arg ReindexDocumentSiblingsParams) error
	ReindexFolderSiblings(ctx context.Context, arg ReindexFolderSiblingsParams) error
	RemoveFolderAccess(ctx context.Context, arg RemoveFolderAccessParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error)
	ResolveFolderAccess(ctx context.Context, arg ResolveFolderAccessParams) (ResolveFolderAccessRow, error)
	RestoreDocument(ctx context.Context, arg RestoreDocumentParams) error
	RestoreDocumentsSweptBy(ctx context.Context, deletedRootFolderID pgtype.UUID) error
	RestoreFolderRoot(ctx context.Context, arg RestoreFolderRootParams) error
	RestoreFoldersSweptBy(ctx context.Context, deletedRootFolderID pgtype.UUID) error
	SearchAllContent(ctx context.Context, arg SearchAllContentParams) ([]SearchAllContentRow, error)
	SearchAllContentPages(ctx context.Context, arg SearchAllContentPagesParams) ([]SearchAllContentPagesRow, error)
	SearchAllDocuments(ctx context.Context, arg SearchAllDocumentsParams) ([]SearchAllDocumentsRow, error)
	SearchAllFolderBreadcrumbs(ctx context.Context, folderIds []pgtype.UUID) ([]SearchAllFolderBreadcrumbsRow, error)
	SearchAllFolders(ctx context.Context, arg SearchAllFoldersParams) ([]SearchAllFoldersRow, error)
	SearchVisibleContent(ctx context.Context, arg SearchVisibleContentParams) ([]SearchVisibleContentRow, error)
	SearchVisibleContentPages(ctx context.Context, arg SearchVisibleContentPagesParams) ([]SearchVisibleContentPagesRow, error)
	SearchVisibleDocuments(ctx context.Context, arg SearchVisibleDocumentsParams) ([]SearchVisibleDocumentsRow, error)
	SearchVisibleFolderBreadcrumbs(ctx context.Context, arg SearchVisibleFolderBreadcrumbsParams) ([]SearchVisibleFolderBreadcrumbsRow, error)
	SearchVisibleFolders(ctx context.Context, arg SearchVisibleFoldersParams) ([]SearchVisibleFoldersRow, error)
	SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error
	SetFolderAccess(ctx context.Context, arg SetFolderAccessParams) (FolderAccess, error)
	SetPageOCRFailure(ctx context.Context, arg SetPageOCRFailureParams) error
	SetPageOCRResult(ctx context.Context, arg SetPageOCRResultParams) error
	SetVersionRendition(ctx context.Context, arg SetVersionRenditionParams) error
	SetVersionRenditionFailure(ctx context.Context, arg SetVersionRenditionFailureParams) error
	SetVersionTextExtracted(ctx context.Context, id pgtype.UUID) error
	SetVersionTextFailure(ctx context.Context, arg SetVersionTextFailureParams) error
	SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error
	SoftDeleteDocumentsForFolderRoot(ctx context.Context, arg SoftDeleteDocumentsForFolderRootParams) error
	SoftDeleteFolderSubtree(ctx context.Context, arg SoftDeleteFolderSubtreeParams) error
}

var _ Querier = (*Queries)(nil)
