// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchAllContent = `-- name: SearchAllContent :many
with q as (
    select
        websearch_to_tsquery('indonesian', $3) as idq,
        websearch_to_tsquery('english', $3) as enq
)
select
    d.id as document_id,
    d.name as document_name,
    d.folder_id,
    f.name as folder_name,
    v.page_count,
    count(*) as hit_count,
    max(greatest(ts_rank(pt.tsv_id, q.idq), ts_rank(pt.tsv_en, q.enq)))::float4 as rank
from documents d
join folders f on f.id = d.folder_id
join document_versions v on v.id = d.current_version_id
join document_page_texts pt on pt.version_id = v.id
cross join q
where d.workspace_id = $1
  and d.deleted_at is null
  and (pt.tsv_id @@ q.idq or pt.tsv_en @@ q.enq)
group by d.id, d.name, d.folder_id, f.name, v.page_count
order by rank desc, d.name
limit $2
`

type SearchAllContentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitCount  int32       `json:"limit_count"`
	Query       string      `json:"query"`
}

type SearchAllContentRow struct {
	DocumentID   pgtype.UUID `json:"document_id"`
	DocumentName string      `json:"document_name"`
	FolderID     pgtype.UUID `json:"folder_id"`
	FolderName   string      `json:"folder_name"`
	PageCount    *int32      `json:"page_count"`
	HitCount     int64       `json:"hit_count"`
	Rank         float32     `json:"rank"`
}

func (q *Queries) SearchAllContent(ctx context.Context, arg SearchAllContentParams) ([]SearchAllContentRow, error) {
	rows, err := q.db.Query(ctx, searchAllContent, arg.WorkspaceID, arg.LimitCount, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllContentRow
	for rows.Next() {
		var i SearchAllContentRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.DocumentName,
			&i.FolderID,
			&i.FolderName,
			&i.PageCount,
			&i.HitCount,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllContentPages = `-- name: SearchAllContentPages :many
with q as (
    select
        websearch_to_tsquery('indonesian', $3) as idq,
        websearch_to_tsquery('english', $3) as enq
)
select
    f.page_no,
    case
        when f.rank_id >= f.rank_en
            then ts_headline('indonesian', f.content, f.idq,
                'MaxFragments=1, MaxWords=30, MinWords=10')
        else ts_headline('english', f.content, f.enq,
            'MaxFragments=1, MaxWords=30, MinWords=10')
    end::text as snippet
from (
    select
        pt.page_no,
        pt.content,
        ts_rank(pt.tsv_id, q.idq) as rank_id,
        ts_rank(pt.tsv_en, q.enq) as rank_en,
        greatest(ts_rank(pt.tsv_id, q.idq), ts_rank(pt.tsv_en, q.enq))::float4 as rank,
        q.idq,
        q.enq
    from document_page_texts pt
    join documents d on d.current_version_id = pt.version_id
    cross join q
    where d.id = $1
      and (pt.tsv_id @@ q.idq or pt.tsv_en @@ q.enq)
    order by rank desc
    limit $2
) f
order by f.rank desc
`

type SearchAllContentPagesParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	LimitCount int32       `json:"limit_count"`
	Query      string      `json:"query"`
}

type SearchAllContentPagesRow struct {
	PageNo  int32  `json:"page_no"`
	Snippet string `json:"snippet"`
}

func (q *Queries) SearchAllContentPages(ctx context.Context, arg SearchAllContentPagesParams) ([]SearchAllContentPagesRow, error) {
	rows, err := q.db.Query(ctx, searchAllContentPages, arg.DocumentID, arg.LimitCount, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllContentPagesRow
	for rows.Next() {
		var i SearchAllContentPagesRow
		if err := rows.Scan(&i.PageNo, &i.Snippet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllDocuments = `-- name: SearchAllDocuments :many
select
    d.id,
    d.name,
    d.folder_id,
    f.name as folder_name,
    v.mime,
    v.size
from documents d
join folders f on f.id = d.folder_id
left join document_versions v on v.id = d.current_version_id
where d.workspace_id = $1
  and d.deleted_at is null
  and d.name ilike '%' || $2 || '%'
order by d.name
limit $3
`

type SearchAllDocumentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Query       *string     `json:"query"`
	LimitCount  int32       `json:"limit_count"`
}

type SearchAllDocumentsRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	FolderID   pgtype.UUID `json:"folder_id"`
	FolderName string      `json:"folder_name"`
	Mime       *string     `json:"mime"`
	Size       *int64      `json:"size"`
}

func (q *Queries) SearchAllDocuments(ctx context.Context, arg SearchAllDocumentsParams) ([]SearchAllDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchAllDocuments, arg.WorkspaceID, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllDocumentsRow
	for rows.Next() {
		var i SearchAllDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.FolderName,
			&i.Mime,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllFolderBreadcrumbs = `-- name: SearchAllFolderBreadcrumbs :many
with recursive chain as (
    select f.id, f.parent_id, f.name, 1 as depth, f.id as root_id, true as visible
    from folders f
    where f.id = any($1::uuid[])
      and f.deleted_at is null
    union all
    select f.id, f.parent_id, f.name, c.depth + 1, c.root_id, true
    from folders f
    join chain c on f.id = c.parent_id
    where f.deleted_at is null
)
select root_id, name, visible
from chain
order by root_id, depth desc
`

type SearchAllFolderBreadcrumbsRow struct {
	RootID  pgtype.UUID `json:"root_id"`
	Name    string      `json:"name"`
	Visible bool        `json:"visible"`
}

func (q *Queries) SearchAllFolderBreadcrumbs(ctx context.Context, folderIds []pgtype.UUID) ([]SearchAllFolderBreadcrumbsRow, error) {
	rows, err := q.db.Query(ctx, searchAllFolderBreadcrumbs, folderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllFolderBreadcrumbsRow
	for rows.Next() {
		var i SearchAllFolderBreadcrumbsRow
		if err := rows.Scan(&i.RootID, &i.Name, &i.Visible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllFolders = `-- name: SearchAllFolders :many
select id, parent_id, name, position, is_default
from folders
where workspace_id = $1
  and deleted_at is null
  and name ilike '%' || $2 || '%'
order by position, name
limit $3
`

type SearchAllFoldersParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Query       *string     `json:"query"`
	LimitCount  int32       `json:"limit_count"`
}

type SearchAllFoldersRow struct {
	ID        pgtype.UUID `json:"id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Position  int32       `json:"position"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) SearchAllFolders(ctx context.Context, arg SearchAllFoldersParams) ([]SearchAllFoldersRow, error) {
	rows, err := q.db.Query(ctx, searchAllFolders, arg.WorkspaceID, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAllFoldersRow
	for rows.Next() {
		var i SearchAllFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVisibleContent = `-- name: SearchVisibleContent :many
with recursive granted as (
    select
        f.id,
        f.parent_id,
        f.name,
        f.position,
        f.is_default,
        f.deleted_at,
        fa.can_view
    from folders f
    join folder_access fa on fa.folder_id = f.id
    join workspace_group_members gm on gm.group_id = fa.group_id
    join workspace_members m on m.id = gm.member_id
    where f.workspace_id = $2
      and m.workspace_id = $2
      and m.user_id = $3

    union all

    select
        c.id,
        c.parent_id,
        c.name,
        c.position,
        c.is_default,
        c.deleted_at,
        g.can_view
    from folders c
    join granted g on c.parent_id = g.id
    where not exists (
        select 1
        from folder_access fa2
        join workspace_group_members gm2 on gm2.group_id = fa2.group_id
        join workspace_members m2 on m2.id = gm2.member_id
        where fa2.folder_id = c.id
          and m2.workspace_id = $2
          and m2.user_id = $3
    )
),
q as (
    select
        websearch_to_tsquery('indonesian', $4) as idq,
        websearch_to_tsquery('english', $4) as enq
)
select
    d.id as document_id,
    d.name as document_name,
    d.folder_id,
    g.name as folder_name,
    v.page_count,
    count(*) as hit_count,
    max(greatest(ts_rank(pt.tsv_id, q.idq), ts_rank(pt.tsv_en, q.enq)))::float4 as rank
from granted g
join documents d on d.folder_id = g.id
    and d.deleted_at is null
    and g.deleted_at is null
join document_versions v on v.id = d.current_version_id
join document_page_texts pt on pt.version_id = v.id
cross join q
where g.can_view
  and (pt.tsv_id @@ q.idq or pt.tsv_en @@ q.enq)
group by d.id, d.name, d.folder_id, g.name, v.page_count
order by rank desc, d.name
limit $1
`

type SearchVisibleContentParams struct {
	LimitCount  int32       `json:"limit_count"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Query       string      `json:"query"`
}

type SearchVisibleContentRow struct {
	DocumentID   pgtype.UUID `json:"document_id"`
	DocumentName string      `json:"document_name"`
	FolderID     pgtype.UUID `json:"folder_id"`
	FolderName   string      `json:"folder_name"`
	PageCount    *int32      `json:"page_count"`
	HitCount     int64       `json:"hit_count"`
	Rank         float32     `json:"rank"`
}

func (q *Queries) SearchVisibleContent(ctx context.Context, arg SearchVisibleContentParams) ([]SearchVisibleContentRow, error) {
	rows, err := q.db.Query(ctx, searchVisibleContent,
		arg.LimitCount,
		arg.WorkspaceID,
		arg.UserID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVisibleContentRow
	for rows.Next() {
		var i SearchVisibleContentRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.DocumentName,
			&i.FolderID,
			&i.FolderName,
			&i.PageCount,
			&i.HitCount,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVisibleContentPages = `-- name: SearchVisibleContentPages :many
with recursive granted as (
    select
        f.id,
        f.parent_id,
        f.name,
        f.position,
        f.is_default,
        f.deleted_at,
        fa.can_view
    from folders f
    join folder_access fa on fa.folder_id = f.id
    join workspace_group_members gm on gm.group_id = fa.group_id
    join workspace_members m on m.id = gm.member_id
    where f.workspace_id = $3
      and m.workspace_id = $3
      and m.user_id = $4

    union all

    select
        c.id,
        c.parent_id,
        c.name,
        c.position,
        c.is_default,
        c.deleted_at,
        g.can_view
    from folders c
    join granted g on c.parent_id = g.id
    where not exists (
        select 1
        from folder_access fa2
        join workspace_group_members gm2 on gm2.group_id = fa2.group_id
        join workspace_members m2 on m2.id = gm2.member_id
        where fa2.folder_id = c.id
          and m2.workspace_id = $3
          and m2.user_id = $4
    )
),
q as (
    select
        websearch_to_tsquery('indonesian', $5) as idq,
        websearch_to_tsquery('english', $5) as enq
)
select
    f.page_no,
    case
        when f.rank_id >= f.rank_en
            then ts_headline('indonesian', f.content, f.idq,
                'MaxFragments=1, MaxWords=30, MinWords=10')
        else ts_headline('english', f.content, f.enq,
            'MaxFragments=1, MaxWords=30, MinWords=10')
    end::text as snippet
from (
    select
        pt.page_no,
        pt.content,
        ts_rank(pt.tsv_id, q.idq) as rank_id,
        ts_rank(pt.tsv_en, q.enq) as rank_en,
        greatest(ts_rank(pt.tsv_id, q.idq), ts_rank(pt.tsv_en, q.enq))::float4 as rank,
        q.idq,
        q.enq
    from granted g
    join documents d on d.folder_id = g.id
        and d.deleted_at is null
        and g.deleted_at is null
    join document_page_texts pt on pt.version_id = d.current_version_id
    cross join q
    where g.can_view
      and d.id = $1
      and (pt.tsv_id @@ q.idq or pt.tsv_en @@ q.enq)
    order by rank desc
    limit $2
) f
order by f.rank desc
`

type SearchVisibleContentPagesParams struct {
	DocumentID  pgtype.UUID `json:"document_id"`
	LimitCount  int32       `json:"limit_count"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	Query       string      `json:"query"`
}

type SearchVisibleContentPagesRow struct {
	PageNo  int32  `json:"page_no"`
	Snippet string `json:"snippet"`
}

func (q *Queries) SearchVisibleContentPages(ctx context.Context, arg SearchVisibleContentPagesParams) ([]SearchVisibleContentPagesRow, error) {
	rows, err := q.db.Query(ctx, searchVisibleContentPages,
		arg.DocumentID,
		arg.LimitCount,
		arg.WorkspaceID,
		arg.UserID,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVisibleContentPagesRow
	for rows.Next() {
		var i SearchVisibleContentPagesRow
		if err := rows.Scan(&i.PageNo, &i.Snippet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVisibleDocuments = `-- name: SearchVisibleDocuments :many
with recursive granted as (
    select
        f.id,
        f.parent_id,
        f.name,
        f.position,
        f.is_default,
        f.deleted_at,
        fa.can_view
    from folders f
    join folder_access fa on fa.folder_id = f.id
    join workspace_group_members gm on gm.group_id = fa.group_id
    join workspace_members m on m.id = gm.member_id
    where f.workspace_id = $3
      and m.workspace_id = $3
      and m.user_id = $4

    union all

    select
        c.id,
        c.parent_id,
        c.name,
        c.position,
        c.is_default,
        c.deleted_at,
        g.can_view
    from folders c
    join granted g on c.parent_id = g.id
    where not exists (
        select 1
        from folder_access fa2
        join workspace_group_members gm2 on gm2.group_id = fa2.group_id
        join workspace_members m2 on m2.id = gm2.member_id
        where fa2.folder_id = c.id
          and m2.workspace_id = $3
          and m2.user_id = $4
    )
)
select
    d.id,
    d.name,
    d.folder_id,
    g.name as folder_name,
    v.mime,
    v.size
from granted g
join documents d on d.folder_id = g.id and d.deleted_at is null
left join document_versions v on v.id = d.current_version_id
where g.can_view
  and d.name ilike '%' || $1 || '%'
order by d.name
limit $2
`

type SearchVisibleDocumentsParams struct {
	Query       *string     `json:"query"`
	LimitCount  int32       `json:"limit_count"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

type SearchVisibleDocumentsRow struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	FolderID   pgtype.UUID `json:"folder_id"`
	FolderName string      `json:"folder_name"`
	Mime       *string     `json:"mime"`
	Size       *int64      `json:"size"`
}

func (q *Queries) SearchVisibleDocuments(ctx context.Context, arg SearchVisibleDocumentsParams) ([]SearchVisibleDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchVisibleDocuments,
		arg.Query,
		arg.LimitCount,
		arg.WorkspaceID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVisibleDocumentsRow
	for rows.Next() {
		var i SearchVisibleDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FolderID,
			&i.FolderName,
			&i.Mime,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVisibleFolderBreadcrumbs = `-- name: SearchVisibleFolderBreadcrumbs :many
with recursive granted as (
    select
        f.id,
        fa.can_view
    from folders f
    join folder_access fa on fa.folder_id = f.id
    join workspace_group_members gm on gm.group_id = fa.group_id
    join workspace_members m on m.id = gm.member_id
    where f.workspace_id = $1
      and m.workspace_id = $1
      and m.user_id = $2

    union all

    select
        c.id,
        g.can_view
    from folders c
    join granted g on c.parent_id = g.id
    where not exists (
        select 1
        from folder_access fa2
        join workspace_group_members gm2 on gm2.group_id = fa2.group_id
        join workspace_members m2 on m2.id = gm2.member_id
        where fa2.folder_id = c.id
          and m2.workspace_id = $1
          and m2.user_id = $2
    )
),
chain as (
    select f.id, f.parent_id, f.name, 1 as depth, f.id as root_id,
        coalesce(g.can_view, false) as visible
    from folders f
    left join granted g on g.id = f.id
    where f.id = any($3::uuid[])
      and f.deleted_at is null
    union all
    select f.id, f.parent_id, f.name, c.depth + 1, c.root_id,
        coalesce(g.can_view, false)
    from folders f
    join chain c on f.id = c.parent_id
    left join granted g on g.id = f.id
    where f.deleted_at is null
)
select root_id, name, visible
from chain
order by root_id, depth desc
`

type SearchVisibleFolderBreadcrumbsParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	UserID      pgtype.UUID   `json:"user_id"`
	FolderIds   []pgtype.UUID `json:"folder_ids"`
}

type SearchVisibleFolderBreadcrumbsRow struct {
	RootID  pgtype.UUID `json:"root_id"`
	Name    string      `json:"name"`
	Visible bool        `json:"visible"`
}

func (q *Queries) SearchVisibleFolderBreadcrumbs(ctx context.Context, arg SearchVisibleFolderBreadcrumbsParams) ([]SearchVisibleFolderBreadcrumbsRow, error) {
	rows, err := q.db.Query(ctx, searchVisibleFolderBreadcrumbs, arg.WorkspaceID, arg.UserID, arg.FolderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVisibleFolderBreadcrumbsRow
	for rows.Next() {
		var i SearchVisibleFolderBreadcrumbsRow
		if err := rows.Scan(&i.RootID, &i.Name, &i.Visible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVisibleFolders = `-- name: SearchVisibleFolders :many
with recursive granted as (
    select
        f.id,
        f.parent_id,
        f.name,
        f.position,
        f.is_default,
        f.deleted_at,
        fa.can_view
    from folders f
    join folder_access fa on fa.folder_id = f.id
    join workspace_group_members gm on gm.group_id = fa.group_id
    join workspace_members m on m.id = gm.member_id
    where f.workspace_id = $3
      and m.workspace_id = $3
      and m.user_id = $4

    union all

    select
        c.id,
        c.parent_id,
        c.name,
        c.position,
        c.is_default,
        c.deleted_at,
        g.can_view
    from folders c
    join granted g on c.parent_id = g.id
    where not exists (
        select 1
        from folder_access fa2
        join workspace_group_members gm2 on gm2.group_id = fa2.group_id
        join workspace_members m2 on m2.id = gm2.member_id
        where fa2.folder_id = c.id
          and m2.workspace_id = $3
          and m2.user_id = $4
    )
)
select id, parent_id, name, position, is_default
from granted
where can_view
  and deleted_at is null
  and name ilike '%' || $1 || '%'
order by position, name
limit $2
`

type SearchVisibleFoldersParams struct {
	Query       *string     `json:"query"`
	LimitCount  int32       `json:"limit_count"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

type SearchVisibleFoldersRow struct {
	ID        pgtype.UUID `json:"id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Position  int32       `json:"position"`
	IsDefault bool        `json:"is_default"`
}

func (q *Queries) SearchVisibleFolders(ctx context.Context, arg SearchVisibleFoldersParams) ([]SearchVisibleFoldersRow, error) {
	rows, err := q.db.Query(ctx, searchVisibleFolders,
		arg.Query,
		arg.LimitCount,
		arg.WorkspaceID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchVisibleFoldersRow
	for rows.Next() {
		var i SearchVisibleFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
