// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: text.sql

package contentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVersionPageText = `-- name: DeleteVersionPageText :exec
delete from document_page_texts where version_id = $1
`

func (q *Queries) DeleteVersionPageText(ctx context.Context, versionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVersionPageText, versionID)
	return err
}

const insertPageText = `-- name: InsertPageText :exec
insert into document_page_texts (version_id, page_no, content)
values ($1, $2, $3)
`

type InsertPageTextParams struct {
	VersionID pgtype.UUID `json:"version_id"`
	PageNo    int32       `json:"page_no"`
	Content   string      `json:"content"`
}

func (q *Queries) InsertPageText(ctx context.Context, arg InsertPageTextParams) error {
	_, err := q.db.Exec(ctx, insertPageText, arg.VersionID, arg.PageNo, arg.Content)
	return err
}

const listPendingOCRPages = `-- name: ListPendingOCRPages :many
select
    d.workspace_id,
    pt.version_id,
    pt.page_no,
    v.rendition_key
from document_page_texts pt
join document_versions v on v.id = pt.version_id
join documents d on d.id = v.document_id
where d.deleted_at is null
  and d.current_version_id = v.id
  and v.text_extracted_at is not null
  and v.rendition_key is not null
  and pt.text_source = 'pdf'
  and pt.ocr_at is null
  and length(trim(pt.content)) < 20
order by d.created_at, pt.version_id, pt.page_no
limit $1
`

type ListPendingOCRPagesRow struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	VersionID    pgtype.UUID `json:"version_id"`
	PageNo       int32       `json:"page_no"`
	RenditionKey *string     `json:"rendition_key"`
}

func (q *Queries) ListPendingOCRPages(ctx context.Context, limitCount int32) ([]ListPendingOCRPagesRow, error) {
	rows, err := q.db.Query(ctx, listPendingOCRPages, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOCRPagesRow
	for rows.Next() {
		var i ListPendingOCRPagesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.VersionID,
			&i.PageNo,
			&i.RenditionKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTextExtraction = `-- name: ListPendingTextExtraction :many
select
    v.id, v.document_id, v.version_no, v.mime, v.size, v.storage_key, v.uploaded_by, v.created_at, v.rendition_key, v.page_count, v.rendition_error, v.rendition_failed_at, v.text_extracted_at, v.text_error, v.text_failed_at,
    d.name as document_name,
    d.workspace_id as workspace_id,
    d.folder_id as folder_id
from document_versions v
join documents d on d.id = v.document_id 
where d.deleted_at is null
    and d.current_version_id = v.id
    and v.text_extracted_at is null
    and v.text_failed_at is null
    and v.rendition_failed_at is null
order by v.created_at
limit $1
`

type ListPendingTextExtractionRow struct {
	ID                pgtype.UUID        `json:"id"`
	DocumentID        pgtype.UUID        `json:"document_id"`
	VersionNo         int32              `json:"version_no"`
	Mime              string             `json:"mime"`
	Size              int64              `json:"size"`
	StorageKey        string             `json:"storage_key"`
	UploadedBy        pgtype.UUID        `json:"uploaded_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	RenditionKey      *string            `json:"rendition_key"`
	PageCount         *int32             `json:"page_count"`
	RenditionError    *string            `json:"rendition_error"`
	RenditionFailedAt pgtype.Timestamptz `json:"rendition_failed_at"`
	TextExtractedAt   pgtype.Timestamptz `json:"text_extracted_at"`
	TextError         *string            `json:"text_error"`
	TextFailedAt      pgtype.Timestamptz `json:"text_failed_at"`
	DocumentName      string             `json:"document_name"`
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	FolderID          pgtype.UUID        `json:"folder_id"`
}

func (q *Queries) ListPendingTextExtraction(ctx context.Context, limit int32) ([]ListPendingTextExtractionRow, error) {
	rows, err := q.db.Query(ctx, listPendingTextExtraction, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTextExtractionRow
	for rows.Next() {
		var i ListPendingTextExtractionRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.VersionNo,
			&i.Mime,
			&i.Size,
			&i.StorageKey,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.RenditionKey,
			&i.PageCount,
			&i.RenditionError,
			&i.RenditionFailedAt,
			&i.TextExtractedAt,
			&i.TextError,
			&i.TextFailedAt,
			&i.DocumentName,
			&i.WorkspaceID,
			&i.FolderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPageOCRFailure = `-- name: SetPageOCRFailure :exec
update document_page_texts
set ocr_error = $1,
    ocr_at = now()
where version_id = $2
  and page_no = $3
`

type SetPageOCRFailureParams struct {
	OcrError  *string     `json:"ocr_error"`
	VersionID pgtype.UUID `json:"version_id"`
	PageNo    int32       `json:"page_no"`
}

func (q *Queries) SetPageOCRFailure(ctx context.Context, arg SetPageOCRFailureParams) error {
	_, err := q.db.Exec(ctx, setPageOCRFailure, arg.OcrError, arg.VersionID, arg.PageNo)
	return err
}

const setPageOCRResult = `-- name: SetPageOCRResult :exec
update document_page_texts
set content = $1,
    words = $2,
    text_source = 'ocr',
    ocr_at = now(),
    ocr_error = null
where version_id = $3
  and page_no = $4
`

type SetPageOCRResultParams struct {
	Content   string      `json:"content"`
	Words     []byte      `json:"words"`
	VersionID pgtype.UUID `json:"version_id"`
	PageNo    int32       `json:"page_no"`
}

func (q *Queries) SetPageOCRResult(ctx context.Context, arg SetPageOCRResultParams) error {
	_, err := q.db.Exec(ctx, setPageOCRResult,
		arg.Content,
		arg.Words,
		arg.VersionID,
		arg.PageNo,
	)
	return err
}

const setVersionTextExtracted = `-- name: SetVersionTextExtracted :exec
update document_versions
set text_extracted_at = now(),
    text_error = null,
    text_failed_at = null
where id = $1
`

func (q *Queries) SetVersionTextExtracted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setVersionTextExtracted, id)
	return err
}

const setVersionTextFailure = `-- name: SetVersionTextFailure :exec
update document_versions
set text_error = $1,
    text_failed_at = now()
where id = $2
`

type SetVersionTextFailureParams struct {
	TextError *string     `json:"text_error"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetVersionTextFailure(ctx context.Context, arg SetVersionTextFailureParams) error {
	_, err := q.db.Exec(ctx, setVersionTextFailure, arg.TextError, arg.ID)
	return err
}
